- .circleci/config.yml
- spec/rails_helper.rb
We want to make Circle:CI run our tests and do auto-deploy. For now just run the tests
> Create Circle:CI configuration just to run 'rake spec'

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- spec/fixtures/vcr_cassettes/IntroPage/is_axe_clean.yml
- spec/rails_helper.rb
- spec/system/intro_page_spec.rb
One test, check for axe_clean - job done. Not sure what else is required.
> Spike axe-core using axe-core-rspec

- README.md
MoJ repositories are all checked for compliancy to the MoJ repo standards. This adds the badge for this repo to show compliancy
> Add MoJ compliancy badge

- .circleci/config.yml
- Gemfile
- app/models/application_record.rb
- bin/setup
- config/application.rb
- spec/rails_helper.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-282)
For now it looks quite likely that the calculator application will not have a local database attached, so remove all references to ActiveRecord to simplify application setup.
> Remove database dependency

- README.md
Add instructions to the README for deploying and managing deployments using helm.
Checklist
> add helm instructions to the README.md

- .circleci/config.yml
- .github/workflows/brakeman-analysis.yml
- config/environments/production.rb
This adds brakeman via a GitHub action for ease of implementation
> Add Brakeman checks

- app/views/build_estimates/assets.html.erb
- spec/features/assets_page_spec.rb
- spec/fixtures/vcr_cassettes/Assets_Page/with_a_mortgage/can_fill_in_the_assets_questions_and_get_to_results.yml
- spec/fixtures/vcr_cassettes/Assets_Page/with_a_mortgage/can_submit_non-zero_savings_and_investments.yml
- spec/fixtures/vcr_cassettes/Assets_Page/with_a_mortgage/can_submit_second_property.yml
- spec/fixtures/vcr_cassettes/Assets_Page/with_a_mortgage/sets_error_on_assets_form.yml
- spec/fixtures/vcr_cassettes/Assets_Page/with_a_mortgage/shows_the_correct_page.yml
- spec/fixtures/vcr_cassettes/Assets_Page/with_no_property/doesnt_show_second_property_question.yml
- spec/fixtures/vcr_cassettes/Assets_Page/with_no_property/shows_the_correct_page.yml
https://dsdmoj.atlassian.net/browse/EL-253
After merging the second part of EL-253, I remembered that the API prevents submission of a second home if there is no first home - so we must not ask the question in that scenario.
> Bug: assets form can't ask second home question if no first home owned

- app/controllers/cookies_controller.rb
- app/views/cookies/show.html.slim
- app/views/layouts/_analytics.html.slim
- app/views/layouts/_cookie_banner.html.slim
- app/views/layouts/_footer.html.slim
- app/views/layouts/application.html.slim
- config/application.rb
- config/locales/en.yml
- config/locales/layouts.yml
- config/routes.rb
- spec/controllers/cookies_controller_spec.rb
- spec/features/cookies_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-323)
This PR:
- Prompts the user to accept or reject non-essential cookies on every screen until the user accepts or rejects non-essential cookies
- Their choice is stored for a year
- If they accept non-essential cookies, we switch on Google Analytics
- They can edit their choice at any time on the new `/cookies` page
Checklist
You should have looked at the diff …
> EL-323: Cookie banner

- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/panel-grey.scss
- app/controllers/provider_users_controller.rb
- app/controllers/referrals_controller.rb
- app/models/provider_user.rb
- app/views/provider_users/show.html.slim
- app/views/referrals/show.html.slim
- app/views/start/index.html.slim
- config/locales/en.yml
- config/routes.rb
- spec/features/property_page_spec.rb
- spec/features/provider_users_page_spec.rb
- spec/requests/provider_users_spec.rb
- spec/requests/referrals_spec.rb
- spec/requests/start_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-363)
Added a branching question page with radio buttons after the start page
Added a referral page for non-legal aid provider users to refer them to alternative sources
Reduce the number of characters used from the branch name to create the release name as it was causing silent deployment failures
Checklist
You should have looked at the diff against main and ensured …
> EL-363 initial branching question

- app/controllers/build_estimates_controller.rb
- app/controllers/flow/employment_handler.rb
- app/forms/employment_form.rb
- app/forms/monthly_income_form.rb
- app/helpers/steps_helper.rb
- app/lib/cfe_connection.rb
- app/models/estimate_data.rb
- app/views/build_estimates/_money_input.html.slim
- app/views/build_estimates/employment.html.slim
- app/views/build_estimates/monthly_income.html.slim
- app/views/build_estimates/summary.html.erb
- app/views/layouts/application.html.slim
- config/locales/en.yml
- spec/features/employment_page_spec.rb
- spec/fixtures/vcr_cassettes/Employment_Page/accessibility/has_no_accessibility_issues.yml
- spec/fixtures/vcr_cassettes/Employment_Page/accessibility/shows_the_correct_page.yml
- spec/fixtures/vcr_cassettes/Employment_Page/allows_me_to_fill_in_the_form_and_move_on.yml
- spec/fixtures/vcr_cassettes/Employment_Page/functionality/allows_me_to_fill_in_the_form_and_move_on.yml
- spec/fixtures/vcr_cassettes/Employment_Page/functionality/shows_the_correct_page.yml
- spec/fixtures/vcr_cassettes/Employment_Page/has_no_accessibility_issues.yml
- spec/fixtures/vcr_cassettes/Employment_Page/shows_the_correct_page.yml
- spec/system/employment_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-351)
This PR does 2 things:
- First, it presents a UI to collect employment income and tax information from the user, as per the prototype designs
- Second, it converts this information to a format understandable by CFE and saves it (note that, as with other CFE calls, this will not produce expected results if the user fills out this screen more than once by use of the back button)
Note that this PR builds on #51 to take advantage of the correction to how we place 'back' buttons on the page
Checklist
There should be no unnecessary whitespace changes. These make …
> EL-351: Employment questions page

- app/views/build_estimates/assets.html.erb
- app/views/build_estimates/monthly_income.html.slim
- app/views/build_estimates/outgoings.html.erb
- app/views/build_estimates/results.html.erb
- app/views/build_estimates/vehicle.html.erb
- app/views/layouts/application.html.slim
- config/locales/en.yml
- spec/system/accessibility_spec.rb
- spec/system/applicant_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-386)
* We now run through every step of the wizard and every non-wizard screen and check for Axe-acceptability
* Tweaked HTML to address issues found by Axe so far.
Checklist
> EL-386: Axe-powered automated accessibility tests 

- app/views/layouts/application.html.slim
- config/locales/en.yml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-387)
Add a 'Beta' phase banner
Checklist
> EL-387: Add phase banner

- app/controllers/flow/monthly_income_handler.rb
- spec/features/monthly_income_page_spec.rb
- spec/fixtures/vcr_cassettes/Outgoings_Page/handles_outgoings.yml
- spec/system/outgoings_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-404)
Stop sending monthly income data when it's submitted, as it gets sent alongside the monthly outgoings data anyway.
> EL-404: Fix double-reporting of monthly income

- app/views/cookies/show.html.slim
- config/environments/test.rb
- config/locales/en.layouts.yml
- config/locales/en.yml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-403)
- Adjusted config so the test runner will raise an exception if the L10n file doesn't contain a key that's requested by the code
- Made immediate fixes to exceptions raised in the exiting test suite.
Checklist
You should have checked that the commit …
> EL-403: Enforce explicit l10n in tests

- config/locales/en.yml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-399)
Add missing translation for error message
Checklist
> el399 add missing error message

- app/controllers/flow/employment_handler.rb
- spec/controllers/cookies_controller_spec.rb
- spec/features/assets_page_spec.rb
- spec/spec_helper.rb
- spec/unit/cfe_connection_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-342)
- Require our tests to cover 100% of code including all parts of inline branches
- Add minimal changes to reach that requirement
Checklist
> EL-342 branching coverage

- app/views/estimate_flow/case_details.html.slim
- config/locales/en.yml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-415)
Removed irrelevant immigration and asylum guidance.
Checklist
> EL-415: Remove irrelevant guidance

- app/forms/applicant_form.rb
- app/views/estimate_flow/applicant.html.slim
- spec/features/applicant_page_spec.rb
- spec/features/assets_page_spec.rb
- spec/features/employment_page_spec.rb
- spec/features/monthly_income_page_spec.rb
- spec/features/property_page_spec.rb
- spec/features/vehicle_page_spec.rb
- spec/support/form_helpers.rb
- spec/system/assets_page_spec.rb
- spec/system/check_answers_page_spec.rb
- spec/system/employment_page_spec.rb
- spec/system/monthly_income_page_spec.rb
- spec/system/outgoings_page_spec.rb
- spec/system/vehicle_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-393)
Commented out partner question and removed all dependencies on it. 
Checklist
> EL-393: Remove partner question

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/results.scss
- app/controllers/estimates_controller.rb
- app/helpers/application_helper.rb
- app/models/calculation_result.rb
- app/views/estimates/show.html.slim
- config/locales/en.yml
- spec/factories/api_results.rb
- spec/features/applicant_page_spec.rb
- spec/features/assets_page_spec.rb
- spec/features/result_page_spec.rb
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
- spec/support/factory_bot.rb
- spec/system/accessibility_spec.rb
https://dsdmoj.atlassian.net/browse/EL-376
Complete implementation of results screen with 3 accordions income, outgoings and capital
> EL-376 complete results screen with client outgoings and capital

- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/button-as-link.scss
- app/controllers/application_controller.rb
- app/controllers/benefits_controller.rb
- app/controllers/estimate_flow_controller.rb
- app/controllers/flow/benefits_handler.rb
- app/forms/benefits_form.rb
- app/helpers/application_helper.rb
- app/lib/cfe_connection.rb
- app/lib/income_section.rb
- app/models/benefit_model.rb
- app/services/cfe_service.rb
- app/services/submit_benefits_service.rb
- app/views/benefits/_form.html.slim
- app/views/benefits/edit.html.slim
- app/views/benefits/new.html.slim
- app/views/estimate_flow/benefits.html.slim
- config/locales/en.yml
- config/routes.rb
- spec/features/applicant_page_spec.rb
- spec/features/benefits_spec.rb
- spec/features/employment_page_spec.rb
- spec/features/result_page_spec.rb
- spec/services/submit_benefits_service_spec.rb
- spec/support/form_helpers.rb
- spec/system/employment_page_spec.rb
- spec/system/monthly_income_page_spec.rb
- spec/system/outgoings_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-352)
New screen to allow client to list benefits
Checklist
> EL-352 create benefits

- config/locales/en.yml
- spec/features/assets_page_spec.rb
- spec/features/property_page_spec.rb
- spec/features/vehicle_page_spec.rb
- spec/system/assets_page_spec.rb
- spec/system/vehicle_page_spec.rb
https://dsdmoj.atlassian.net/browse/EL-420
Change heading on check your answers screen
> EL-420 change check your answers heading

- app/forms/assets_form.rb
- app/lib/check_answers_fields.yml
- app/services/check_answers/section_lister_service.rb
- app/services/submit_assets_service.rb
- app/views/estimate_flow/assets.html.slim
- app/views/estimates/_client_capital_table.html.slim
- config/locales/en.yml
- spec/features/applicant_page_spec.rb
- spec/features/assets_page_spec.rb
- spec/features/property_page_spec.rb
- spec/features/result_page_spec.rb
- spec/features/vehicle_page_spec.rb
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
- spec/forms/assets_form_spec.rb
- spec/support/form_helpers.rb
- spec/system/accessibility_spec.rb
- spec/system/assets_page_spec.rb
- spec/system/check_answers_page_spec.rb
- spec/system/vehicle_page_spec.rb
https://dsdmoj.atlassian.net/browse/EL-417
Remove checkbox reveals from assets page, and instead display all sections to be filled in with zeroes
> EL-417 new assets page without checkboxes

- app/controllers/benefits_controller.rb
- app/controllers/check_benefits_answers_controller.rb
- app/helpers/application_helper.rb
- app/lib/check_answers_fields.yml
- app/models/benefit_model.rb
- app/services/check_answers/section_lister_service.rb
- app/views/benefits/_form.html.slim
- app/views/benefits/edit.html.slim
- app/views/benefits/new.html.slim
- app/views/estimate_flow/_money_check_answer.html.slim
- app/views/estimate_flow/benefits.html.slim
- app/views/estimate_flow/check_answers.html.slim
- config/routes.rb
- spec/features/benefits_spec.rb
- spec/features/check_answers_page_spec.rb
- spec/features/result_page_spec.rb
- spec/support/form_helpers.rb
- spec/system/employment_page_spec.rb
- spec/system/monthly_income_page_spec.rb
- spec/system/outgoings_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-411)
Allow individually entered benefits to be shown on the 'Check Answers' screen
Checklist
> EL-411: Check benefits answers

- app/services/submit_proceedings_service.rb
Remove session data knowledge from CFE layer
> Refactor to remove knowledge of proceeding type key from Cfe Layer

- app/views/layouts/application.html.slim
- app/views/layouts/print_application.html.slim
- public/robots.txt
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-434)
- Update robots.txt to ask Google not to crawl any pages
- Add noindex meta to ask Google not to index any pages linked from elsewhere.
Checklist
> EL-434: Request search engines do not index

- app/helpers/build_estimates_helper.rb
- app/views/shared/_sidebar_with_date.html.slim
- config/locales/en.yml
https://dsdmoj.atlassian.net/browse/EL-435
Property with mortgage option is supposed to be before owned_outright
> EL-435 re-order property prompt options to match prototype

- app/assets/stylesheets/application.sass.scss
- app/lib/check_answers_fields.yml
- app/services/check_answers/section_lister_service.rb
- app/views/estimate_flow/_check_answer.html.slim
- app/views/estimate_flow/_money_check_answer.html.slim
- app/views/estimate_flow/assets.html.slim
- app/views/estimate_flow/check_answers.html.slim
- config/locales/en.yml
- package.json
- spec/features/assets_page_spec.rb
- spec/features/property_page_spec.rb
- spec/features/vehicle_page_spec.rb
- yarn.lock
https://dsdmoj.atlassian.net/browse/EL-432
Add SMOD assets to check answers screen by displaying a badge
> EL-432 SMOD assets on check answers screen using moj-badge

- app/assets/stylesheets/results.scss
- app/models/calculation_result.rb
- app/views/estimates/show.html.slim
- config/locales/en.yml
https://dsdmoj.atlassian.net/browse/EL-427
Change confirmation panel colour to blue to be a neutral colour as the outcome can be 'unsuccessful'
> EL-427 change confirmation panel to a neutral blue colour

- config/locales/en.yml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-407)
As identified by Lel during UAT and added as a comment on the original ticket. Original PR was merged before the comment was noticed.
Update the link so it points to the specific piece of guidance
Checklist
You should have checked that the commit …
> EL-407 bugfix update link to direct user to specific page

- app/forms/assets_form.rb
- app/lib/cfe_connection.rb
- app/services/submit_assets_service.rb
- app/views/estimate_flow/assets.html.slim
- config/locales/en.yml
- spec/features/assets_page_spec.rb
https://dsdmoj.atlassian.net/browse/EL-431
Add Subject matter of dispute checkboxes to the rest of the assets page
> EL-431 non-property Assets in dispute

- app/helpers/application_helper.rb
- app/views/estimate_flow/applicant.html.slim
- app/views/estimate_flow/case_details.html.slim
- app/views/estimate_flow/dependant_details.html.slim
- app/views/estimate_flow/dependants.html.slim
- app/views/estimate_flow/outgoings.html.slim
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-439)
Some of the back buttons were leading to the wrong places. Some were not behaving correctly in the check answers flow. One was just causing the screen to reload. This PR fixes these up.
> EL-439: Fix variously broken back buttons

- app/forms/vehicle_details_form.rb
- app/lib/cfe_connection.rb
- app/services/submit_vehicle_service.rb
- app/views/estimate_flow/vehicle_details.html.slim
- config/locales/en.yml
- spec/features/vehicle_page_spec.rb
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
- spec/fixtures/vcr_cassettes/Vehicle_Page/CFE_submission/handles_a_full_submit_to_CFE.yml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-430)
Add a 'smod' checkbox to the vehicle details page.
Send a subject_matter_of_dispute flag to CFE when describing vehicle if the checkbox is checked
Checklist
> EL-430: Add SMOD checkbox to vehicles page

- app/helpers/application_helper.rb
I accidentally broke main by not rebasing before merging EL-439
> Unbreak check answers back link

- app/controllers/benefits_controller.rb
- app/controllers/check_answers_controller.rb
- app/controllers/check_benefits_answers_controller.rb
- app/controllers/estimate_flow_controller.rb
- app/lib/steps_helper.rb
- spec/features/change_employment_type_spec.rb
- spec/features/check_answers_page_spec.rb
- spec/support/form_helpers.rb
https://dsdmoj.atlassian.net/browse/EL-388
More complex check answers behaviour. If check answers screen results in the need to answer other questions, those questions are now answered in turn so that by the time the user returns to the check answers screen the data set is valid again
> EL-388: Complex check answers behaviour

- app/controllers/estimate_flow_controller.rb
- app/controllers/flow/applicant_handler.rb
- app/controllers/flow/partner_handler.rb
- app/forms/applicant_form.rb
- app/forms/partner_form.rb
- app/lib/applicant_case_details_section.rb
- app/lib/check_answers_fields.yml
- app/services/check_answers/section_lister_service.rb
- app/views/estimate_flow/applicant.html.slim
- app/views/estimate_flow/partner.html.slim
- config/locales/en.yml
- spec/features/applicant_page_spec.rb
- spec/features/partner_page_spec.rb
- spec/support/form_helpers.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-475)
Add new initial partner questions.
> EL-475: Add new partner questions

- spec/features/vehicle_page_spec.rb
Add a missing test to check the anchor during the complex vehicle check answers loop
> Add a test for the anchor during the vehicle check answers loop

- app/views/layouts/_footer.html.slim
- app/views/layouts/application.html.slim
- app/views/layouts/print_application.html.slim
- config/locales/en.layouts.yml
- config/locales/en.yml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-454)
Add mailto feedback links to header and footer
> EL-454: Feedback links

- app/controllers/benefits_controller.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-478)
Set session var correctly
> EL-478: BUG - check answers flow leads back to the benefits page

- app/forms/client_assets_form.rb
- app/lib/cfe_connection.rb
- app/services/base_cfe_service.rb
- app/services/cfe_param_builders/capitals.rb
- app/services/cfe_param_builders/employments.rb
- app/services/cfe_param_builders/irregular_income.rb
- app/services/cfe_param_builders/regular_transactions.rb
- app/services/cfe_param_builders/state_benefits.rb
- app/services/cfe_param_builders/vehicles.rb
- app/services/cfe_service.rb
- app/services/submit_applicant_service.rb
- app/services/submit_assets_service.rb
- app/services/submit_benefits_service.rb
- app/services/submit_dependants_service.rb
- app/services/submit_employment_income_service.rb
- app/services/submit_irregular_income_service.rb
- app/services/submit_partner_service.rb
- app/services/submit_proceedings_service.rb
- app/services/submit_regular_transactions_service.rb
- app/services/submit_vehicle_service.rb
- spec/features/assets_page_spec.rb
- spec/features/vehicle_page_spec.rb
- spec/fixtures/vcr_cassettes/Assets_Page/has_no_AXE-detectable_accessibility_issues.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
- spec/services/submit_partner_service_spec.rb
- spec/unit/cfe_connection_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-469)
Refactor param-building logic into separate classes
Reuse the param-building logic to construct a payload to send partner information to CFE
> EL-469: Send partner data to CFE

- app/models/calculation_result.rb
- app/views/estimates/_client_capital_table.html.slim
- config/locales/en.yml
- spec/features/assets_page_spec.rb
- spec/features/dependants_pages_spec.rb
- spec/features/employment_page_spec.rb
- spec/features/other_income_page_spec.rb
- spec/features/property_page_spec.rb
- spec/features/result_page_spec.rb
- spec/features/vehicle_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-442)
Display more values around capital items so that the calculation is clear
make sections conditional to show only if values exist
I expect that during UAT there will be some more work required to tweak what is displayed on this page or the order in which it is displayed.
Checklist
You should have looked at the diff against main and ensured that nothing unexpected is …
> El 442 display calculations on results page

- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
- spec/system/accessibility_spec.rb
- spec/system/assets_page_spec.rb
- spec/system/employment_page_spec.rb
- spec/system/error_page_spec.rb
- spec/system/outgoings_page_spec.rb
- spec/system/vehicle_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-447)
System tests are now tested headlessly so that developer machines aren't taken over by flickery Chrome popups for a minute every test run.
Checklist
> EL-447: Use headless tests

- spec/features/applicant_page_spec.rb
- spec/features/check_answers_page_spec.rb
- spec/features/partner_assets_page_spec.rb
- spec/features/partner_benefits_spec.rb
- spec/features/partner_employment_page_spec.rb
- spec/features/partner_other_income_page_spec.rb
- spec/features/partner_outgoings_page_spec.rb
- spec/features/partner_page_spec.rb
- spec/features/partner_vehicle_pages_spec.rb
- spec/rails_helper.rb
- spec/support/form_helpers.rb
DRY up usage of partner flag in tests
> DRY partner flag usage

- app/controllers/privacies_controller.rb
- app/views/layouts/_footer.html.slim
- app/views/privacies/show.html.slim
- config/locales/en.layouts.yml
- config/locales/en.yml
- config/routes.rb
- spec/system/accessibility_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-322)
Update footer and add privacy page.
> EL-322: Update footer

- app/views/cookies/show.html.slim
- app/views/layouts/application.html.slim
- app/views/start/index.html.slim
- config/locales/en.yml
https://dsdmoj.atlassian.net/browse/EL-379
Change service name to reflect new name
> EL-379 Change service name

- app/views/estimates/print.html.slim
- app/views/start/index.html.slim
- config/locales/en.yml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-510)
Update copy on the start page.
> EL-510 start page copy

- app/controllers/status_controller.rb
- app/lib/cfe_connection.rb
- app/services/health_check_service.rb
- config/routes.rb
- helm_deploy/laa-estimate-eligibility/templates/deployment.yaml
- spec/requests/statuses_controller_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-499)
- Create a new endpoint that verifies CFE and Redis are working as expected
- Tell Kubernetes to use that endpoint to check instance readiness
> EL-499: Kubernetes probes

- spec/requests/statuses_controller_spec.rb
> Use correct endpoint in new tests

- app/views/layouts/application.html.slim
- app/views/layouts/print_application.html.slim
- config/locales/en.yml
https://dsdmoj.atlassian.net/browse/EL-338
Link to user survey in Beta banner
> EL-338 link to user survey in Beta banner

- app/services/check_answers/section_lister_service.rb
https://dsdmoj.atlassian.net/browse/EL-513
Remove partner_benefits section when no partner so that partner_other_income section collapses to nothing
> EL-513 don't show partner_other_income section when no partner

- app/views/benefits/new.html.slim
- app/views/estimate_flow/_partner_property_sidebar.html.slim
- app/views/estimate_flow/_property_sidebar.html.slim
- app/views/estimate_flow/applicant.html.slim
- app/views/estimate_flow/assets.html.slim
- app/views/estimate_flow/case_details.html.slim
- app/views/estimate_flow/partner.html.slim
- app/views/estimate_flow/property_entry.html.slim
- app/views/estimates/show.html.slim
- app/views/provider_users/show.html.slim
- app/views/start/index.html.slim
- config/locales/en.yml
https://dsdmoj.atlassian.net/browse/EL-504
Add content from content designer - client (non-partner) only for this pass
> EL-504 client content

- app/views/referrals/show.html.slim
- config/locales/en.yml
https://dsdmoj.atlassian.net/browse/EL-504
> EL-504 take II - last piece of content for service not applicable page

- app/controllers/check_answers_controller.rb
- app/controllers/check_benefits_answers_controller.rb
- app/controllers/check_partner_benefits_answers_controller.rb
- app/services/check_answers/section_id_finder.rb
- spec/features/vehicle_page_spec.rb
- spec/services/check_answers/section_id_finder_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-507)
Add a list of sections describing exactly which HTML element should be anchored when returning to the Check Answers screen.
> EL-507: more precise sections

- app/views/layouts/_cookie_banner.html.slim
- config/locales/en.yml
- spec/features/cookies_spec.rb
https://dsdmoj.atlassian.net/browse/EL-528
Use new service name in cookie banner
> EL-528 fix up service name in cookie banner

- app/controllers/flow/handler.rb
- app/forms/partner_housing_benefit_details_form.rb
- app/forms/partner_housing_benefit_form.rb
- app/lib/check_answers_fields.yml
- app/lib/income_section.rb
- app/lib/partner_income_section.rb
- app/models/estimate_model.rb
- app/services/cfe_param_builders/state_benefits.rb
- app/services/check_answers/section_id_finder.rb
- app/services/submit_partner_service.rb
- app/views/estimate_flow/partner_housing_benefit.html.slim
- app/views/estimate_flow/partner_housing_benefit_details.html.slim
- config/locales/en.yml
- spec/features/check_answers_page_spec.rb
- spec/features/partner_assets_page_spec.rb
- spec/features/partner_benefits_spec.rb
- spec/features/partner_housing_benefit_pages_spec.rb
- spec/features/partner_other_income_page_spec.rb
- spec/features/partner_outgoings_page_spec.rb
- spec/features/partner_vehicle_pages_spec.rb
- spec/features/result_page_spec.rb
- spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_client_income_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_capital_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_outgoings_section.yml
- spec/support/form_helpers.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-517)
Added the partner equivalent of the new housing benefit screens
> EL-517: Partner housing benefit

- Gemfile.lock
- app/services/submit_employment_income_service.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-533)
If someone unchecks 'employed' we don't want to send their previously salary breakdown to CFE.
Checklist
> EL-533: Only submit employment data if client is employed

- app/views/estimate_flow/_partner_property_sidebar.html.slim
- app/views/estimate_flow/_property_sidebar.html.slim
- app/views/estimate_flow/vehicle.html.slim
- app/views/estimate_flow/vehicle_details.html.slim
- app/views/shared/_sidebar_with_date.html.slim
- config/locales/en.yml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-527)
* Update content
* Remove leading zero from dates
> EL-527: Update content

- app/views/provider_users/show.html.slim
- config/locales/en.yml
https://dsdmoj.atlassian.net/browse/EL-555
> EL-555 add date to provider question screen

- app/views/estimate_flow/forms/_outgoings.html.slim
- config/locales/en.yml
https://dsdmoj.atlassian.net/browse/EL-559
Rework housing costs help text, and improve layout to closer match expected screen when multiple sentences are being used
> EL-559 rework housing costs help text

- app/views/estimate_flow/forms/_dependant_details.html.slim
- config/locales/en.yml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-556)
Richer help-text
> EL-556: New dependant helptext

- app/lib/cfe_connection.rb
https://dsdmoj.atlassian.net/browse/EL-558
Need to cope with the JSON parser failing to parse a 502 error response so that Faraday can retry nicely
> EL-558 cope/retry with invalid JSON responses from CFE

- README.md
The repo standards badge has been reporting Fail (possibly forever, it looks like it comes from the repository template)
This fixes the badge and links to the correct report/repo
Checklist
> update MoJ compliant badge

- app/views/benefits/new.html.slim
- app/views/estimate_flow/_add_benefit_form.html.slim
- app/views/estimate_flow/benefits.html.slim
- app/views/estimate_flow/partner_benefits.html.slim
- app/views/shared/_disregarded_benefits.html.slim
- app/views/shared/_three_headings.html.slim
- config/locales/en.yml
- spec/features/benefits_spec.rb
- spec/features/check_answers_page_spec.rb
- spec/features/partner_benefits_spec.rb
- spec/support/form_helpers.rb
https://dsdmoj.atlassian.net/browse/EL-532
> EL-532 add 'blind' component for disregarded benefits

- .circleci/config.yml
- infrastructure/laa-estimate-financial-eligibility-for-legal-aid-uat/ingress-dashboard.yaml
Discussion: https://mojdt.slack.com/archives/C040DEGBZQQ/p1671036332937119
No specific Jira ticket, but piggybacks onto EL-535
The dashboard YAML has had it's title reworked:
```
<       "description": "Check if your client qualifies for legal aid - UAT - Ingress",
---
>       "description": "CCQ Ingress (Check if your client qualifies for legal aid)",
```
because Grafana truncates the view:
This PR also changes a couple of IDs, so that this dashboard can co-exist with the existing one temporarily.
All changes compared to the environments repo:
```
% diff ~/code/cloud-platform-environments/namespaces/live.cloud-platform.service.justice.gov.uk/laa-estimate-financial-eligibility-for-legal-aid-uat/05-dashboard.yaml infrastructure/laa-estimate-financial-eligibility-for-legal-aid-uat/ingress-da …
```
> Grafana dashboard moved here from environments repo

- app/views/estimate_flow/employment.html.slim
- app/views/estimate_flow/forms/_employment.html.slim
- app/views/shared/_money_input.html.slim
- config/locales/en.yml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-562)
Update size of labels to match first field, adjust content and amend spacing below each field in the employment input fields
Checklist
> EL-562 update income labels and spacing

- infrastructure/laa-estimate-financial-eligibility-for-legal-aid-uat/ingress-dashboard.yaml
- infrastructure/laa-estimate-financial-eligibility-for-legal-aid-uat/pods-dashboard.yaml
Also, the filename in grafana dashbaords needs to be unique, or they start 404ing
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-560)
> EL-560 Move pod dashboard from environments repo

- app/views/estimate_flow/partner_property.html.slim
- app/views/estimate_flow/partner_vehicle.html.slim
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-591)
Fix indentation of subheaders
[EL-591]: https://dsdmoj.atlassian.net/browse/EL-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EL-591: Subheader font

- app/views/benefits/new.html.slim
- app/views/estimate_flow/_add_benefit_form.html.slim
- app/views/estimate_flow/benefits.html.slim
- app/views/estimate_flow/forms/_assets.html.slim
- app/views/estimate_flow/forms/_other_income.html.slim
- app/views/estimate_flow/partner_benefits.html.slim
- app/views/partner_benefits/new.html.slim
- app/views/shared/_cost_of_living.html.slim
- app/views/shared/_disregarded_benefits.html.slim
- config/locales/en.yml
- spec/features/partner_benefits_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-570)
Note, please do not deploy this to production before 10 Jan 2023. Yes, this is not ideal, but the mechanism to introduce copy changes automatically on specific dates has not yet been built.
[EL-570]: https://dsdmoj.atlassian.net/browse/EL-570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> EL-570: Add cost of living wording

- README.md
- app/forms/applicant_form.rb
- app/lib/feature_flags.rb
- app/services/check_answers/applicant_section.rb
- app/services/submit_partner_service.rb
- app/views/estimate_flow/applicant.html.slim
- app/views/estimate_flow/benefits.html.slim
- app/views/estimate_flow/forms/_assets.html.slim
- app/views/estimate_flow/forms/_other_income.html.slim
- app/views/estimate_flow/partner_benefits.html.slim
- app/views/shared/_cost_of_living.html.slim
- app/views/shared/_disregarded_benefits_details.html.slim
- app/views/start/index.html.slim
- config/initializers/flipper.rb
- config/locales/en.yml
- spec/lib/feature_flags_spec.rb
- spec/support/navigation_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-604)
This PR re-implements #326 using a new time-based scheduling mechanism to show cost-of-living content only on or after the go-live date. 
> EL-604: Scheduled changes

- app/views/estimate_flow/partner_assets.html.slim
- app/views/estimate_flow/partner_employment.html.slim
- config/locales/en.yml
- spec/features/check_answers_page_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-600)
Content updates
> EL-600: Other income, outgoings and check answers

- app/views/estimate_flow/applicant.html.slim
- app/views/estimate_flow/assets.html.slim
- app/views/estimate_flow/dependant_details.html.slim
- app/views/estimate_flow/forms/_dependant_details.html.slim
- app/views/estimate_flow/partner_dependant_details.html.slim
- app/views/estimate_flow/partner_details.html.slim
- config/locales/en.yml
- spec/features/assets_page_spec.rb
- spec/features/change_employment_type_spec.rb
- spec/features/employment_page_spec.rb
- spec/features/other_income_page_spec.rb
- spec/features/outgoings_page_spec.rb
- spec/features/partner_dependants_pages_spec.rb
- spec/features/partner_employment_page_spec.rb
- spec/features/vehicle_page_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-598)
A big bunch of copy updates per the ticket description.
> EL-598: Assets, outgoings and dependants pages

- config/locales/en.yml
- spec/features/property_page_spec.rb
https://dsdmoj.atlassian.net/browse/EL-596
Change client property content to match partner content
> EL-596 property content

- config/locales/en.yml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-597)
A list of small content changes to the client and partner vehicle pages
> EL-597: Content changes for vehicle pages

- app/views/accessibilities/_list.html.slim
- app/views/accessibilities/show.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-606)
Update accessibility statement to reflect we now passed the audit.
> EL-606: Update accessibility statement

- config/locales/en.yml
https://dsdmoj.atlassian.net/browse/EL-605
Content changes for Partner property screen
> EL-605 Partner Property content

- app/views/estimate_flow/applicant.html.slim
- app/views/estimate_flow/forms/_dependant_details.html.slim
- config/locales/en.yml
- spec/features/benefits_spec.rb
- spec/features/other_income_page_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-595)
Update content for applicant details and dependants pages conditional on existence of partner
> EL-595 content changes for applicant details and dependants

- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-627)
Content tweaks
> EL-627: Content cleanup

- app/controllers/cookies_controller.rb
- config/environments/production.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-616)
Set more secure values on cookies
> EL-616: Cookie config

- app/forms/base_assets_form.rb
- app/forms/other_income_form.rb
- app/forms/outgoings_form.rb
- config/locales/en.yml
- spec/features/applicant_page_spec.rb
- spec/features/employment_page_spec.rb
- spec/features/partner_dependants_pages_spec.rb
- spec/features/partner_vehicle_pages_spec.rb
- spec/features/property_page_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-635)
Updated error message content on client and partner flows
added validation for negative values for some assets/outgoings
Tweaked validation elsewhere to properly display messages detailed in the spreadsheet
> EL-635 Error content and validation changes for partner flow

- config/initializers/filter_parameter_logging.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-654)
We don't want anything remotely resembling PII or personal information in our logs
> EL-654 Filter out all params from logs

- app/lib/cfe_connection.rb
- app/services/cfe_service.rb
- spec/features/level_of_help_page_spec.rb
- spec/support/navigation_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-659)
Tell CFE if the user specifies a level of help
> EL-659: Tell CFE about the level of help

- app/forms/applicant_form.rb
- app/services/check_answers/applicant_section.rb
- app/services/submit_proceedings_service.rb
- app/views/estimate_flow/applicant.html.slim
- spec/support/navigation_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-643)
Remove one piece of guidance and hide domestic abuse question if the level of help is controlled.
> EL-643: Controlled applicant pages

- app/views/estimate_flow/applicant.html.slim
- app/views/estimate_flow/dependant_details.html.slim
- app/views/estimate_flow/partner_dependant_details.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-669)
The guidance for controlled work is in a different place to certificate work.
> EL-669: Guidance links

- app/lib/capital_section.rb
- app/lib/partner_capital_section.rb
- app/models/calculation_result.rb
- app/models/estimate_model.rb
- app/services/cfe_service.rb
- app/views/estimate_flow/partner_details.html.slim
- app/views/estimates/_capital_table.html.slim
- config/locales/en.yml
- spec/features/level_of_help_page_spec.rb
- spec/support/navigation_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-648)
For controlled work show no vehicle screens nor a vehicle subtotal on the results page
> EL-648 remove vehicle screens

- app/forms/outgoings_form.rb
- app/forms/partner_outgoings_form.rb
- app/views/estimate_flow/outgoings.html.slim
- app/views/estimate_flow/partner_outgoings.html.slim
- config/locales/en.yml
- spec/features/level_of_help_page_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-647)
New guidance link and text, and removed frequency option
> EL-647: Update outgoings page for controlled work

- app/forms/other_income_form.rb
- app/forms/partner_other_income_form.rb
- app/services/cfe_param_builders/irregular_income.rb
- app/views/estimate_flow/forms/_other_income.html.slim
- config/locales/en.yml
- spec/features/other_income_page_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-646)
- Remove 3-monthly frequency from regular other incomes
- Change instruction text for irregular income
- Change frequency as pushed to CFE for irregular income
- N.B this PR relies on a corresponding change to CFE: https://github.com/ministryofjustice/check-financial-eligibility-partner/pull/75
> EL-646: Other income for controlled work

- app/views/start/index.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-666)
New start page for controlled work
> EL-666: New start page for controlled work

- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-661)
We have now decided on the wording for the check answers screen, and it's nearly what I put in as a placeholder, so not much needs to change.
> EL-661: Change wording for level of help on check answers

- app/assets/stylesheets/results.scss
- app/models/calculation_result.rb
- app/views/estimates/_contribution_required.html.slim
- app/views/estimates/_eligible.html.slim
- app/views/estimates/_ineligible.html.slim
- app/views/estimates/print.html.slim
- app/views/estimates/show.html.slim
- config/locales/en.yml
- spec/features/assets_page_spec.rb
- spec/features/result_page_spec.rb
- spec/models/calculation_result_spec.rb
- spec/system/partner_passporting_spec.rb
- spec/system/vehicle_page_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-619)
Updated the blue panel on the results screen (and top section on the print screen) with new copy
> EL-619: New confirmation panel on results page

- app/views/estimate_flow/forms/_assets.html.slim
- app/views/estimate_flow/property_entry.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-679)
Minor controlled content changes
> EL-679: Content cleanup

- app/models/calculation_result.rb
- app/views/estimate_flow/_certificated_property_sidebar.html.slim
- app/views/estimate_flow/_controlled_property_sidebar.html.slim
- app/views/estimate_flow/assets.html.slim
- app/views/estimate_flow/partner_assets.html.slim
- app/views/estimate_flow/vehicle_details.html.slim
- config/locales/en.yml
- spec/features/property_page_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-665)
Make the guidance conditional on the journey type
> EL 665 journey specific asset guidance

- app/controllers/accessibilities_controller.rb
- app/controllers/application_controller.rb
- app/controllers/benefits_controller.rb
- app/controllers/build_estimates_controller.rb
- app/controllers/check_answers_controller.rb
- app/controllers/check_benefits_answers_controller.rb
- app/controllers/cookies_controller.rb
- app/controllers/estimate_flow_controller.rb
- app/controllers/estimates_controller.rb
- app/controllers/privacies_controller.rb
- app/controllers/provider_users_controller.rb
- app/controllers/referrals_controller.rb
- app/controllers/start_controller.rb
- app/services/analytics_service.rb
- app/views/cookies/show.html.slim
- config/locales/en.yml
- config/routes.rb
- spec/controllers/cookies_controller_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-682)
Log page views and validation messages
> EL-682: Add additional logging for analytics purposes

- app/lib/feature_flags.rb
- app/views/estimate_flow/benefits.html.slim
- app/views/estimate_flow/forms/_assets.html.slim
- app/views/estimate_flow/forms/_other_income.html.slim
- app/views/estimate_flow/partner_benefits.html.slim
- app/views/shared/_cost_of_living.html.slim
- app/views/shared/_disregarded_benefits_details.html.slim
- config/locales/en.yml
https://dsdmoj.atlassian.net/browse/EL-678
> EL-678 remove cost of living feature flag

- app/lib/cfe_connection.rb
- app/models/benefit_model.rb
- spec/features/benefits_spec.rb
- spec/features/check_answers_page_spec.rb
- spec/features/partner_benefits_spec.rb
- spec/unit/cfe_connection_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-681)
remove the disregarded and passported benefits from the list returned by cfe before we display it as suggestions
> EL-681 remove disregarded and passported benefits from suggestions

- app/views/start/index.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-703)
Remove references to upper tribunal not being allowed where not appropriate
> EL-703: Upper tribunal start page

- app/views/referrals/show.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-561)
Tweak content on referral page
> EL-561: Content on referral page

- helm_deploy/laa-estimate-eligibility/values/staging.yaml
Enable controlled work on staging for internal testing.
> Enable controlled work on staging

- app/views/estimate_flow/level_of_help.html.slim
- app/views/shared/_question_sidebar.html.slim
- app/views/shared/_related_content.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-708)
New level of help content
> EL-708: New level of help content

- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-714)
Update controlled evidence wording
> EL-714: Update controlled evidence wording

- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-721)
Sentry is working again. I have rate limited our live keys to process 10 events an hour, and this can be adjusted easily via the Sentry UI
> EL-721: Enable Sentry

- app/models/calculation_result.rb
- spec/factories/api_results.rb
- spec/features/result_page_spec.rb
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
- spec/models/calculation_result_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-712)
More accurate evaluation of main home equity disregard
> EL-712: Main home equity disregard always displays as £100k.

- app/views/estimate_flow/forms/_dependant_details.html.slim
- app/views/estimate_flow/forms/_outgoings.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-640)
Wording updates following caseworker testing
> El 640: wording updates

- app/models/calculation_result.rb
- config/locales/en.yml
- spec/factories/api_results.rb
- spec/features/result_page_spec.rb
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_client_income_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_outgoings_section.yml
- spec/models/calculation_result_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-711)
Show new deductions row for main properties when there are deductions
Also don't show cost of sale deductions for additional properties when there are none (e.g. for controlled work cases)
> EL-711: Cost of sale bug

- .circleci/config.yml
- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
- app/lib/exception_notifier/templated_notifier.rb
- app/models/analytics_event.rb
- app/models/application_record.rb
- app/services/analytics_service.rb
- app/services/error_service.rb
- config/application.rb
- config/database.yml
- db/migrate/20230221125618_create_analytics_events.rb
- db/schema.rb
- spec/features/result_page_spec.rb
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/records_every_step_of_the_journey_in_analytics_events.yml
- spec/services/analytics_service_spec.rb
- spec/services/error_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-713)
We now keep analytics in a postgres database.
> EL-713: Start using postgres to record analytics

- app/controllers/flow/handler.rb
- app/forms/applicant_form.rb
- app/forms/asylum_support_form.rb
- app/lib/applicant_details_section.rb
- app/lib/capital_section.rb
- app/lib/case_details_section.rb
- app/lib/check_answers_fields.yml
- app/lib/income_section.rb
- app/lib/partner_capital_section.rb
- app/lib/partner_income_section.rb
- app/lib/partner_section.rb
- app/lib/steps_helper.rb
- app/models/estimate_model.rb
- app/services/cfe_service.rb
- app/services/check_answers/section_id_finder.rb
- app/services/submit_applicant_service.rb
- app/services/submit_assets_service.rb
- app/views/estimate_flow/asylum_support.html.slim
- config/locales/en.yml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
- spec/features/asylum_and_immigration_spec.rb
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_client_income_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_capital_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_outgoings_section.yml
- spec/fixtures/vcr_cassettes/Vehicle_Page/CFE_submission/handles_a_full_submit_to_CFE.yml
- spec/services/submit_applicant_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-696)
Add in asylum support page, translations and check answers
Splits the ApplicantCaseDetailsSection into ApplicantDetailsSection and CaseDetailsSection as the current section was heavily weighted towards case and not applicant. Happy to revert this if anyone feel sit is unnecessary.
> EL-696 passporting asylum support applications

- app/forms/applicant_form.rb
- app/forms/matter_type_form.rb
- app/helpers/applicant_helper.rb
- app/helpers/matter_type_helper.rb
- app/lib/applicant_details_section.rb
- app/lib/capital_section.rb
- app/lib/case_details_section.rb
- app/lib/check_answers_fields.yml
- app/lib/income_section.rb
- app/lib/partner_capital_section.rb
- app/lib/partner_income_section.rb
- app/lib/partner_section.rb
- app/models/estimate_model.rb
- app/services/submit_assets_service.rb
- app/services/submit_proceedings_service.rb
- app/views/estimate_flow/applicant.html.slim
- app/views/estimate_flow/matter_type.html.slim
- config/locales/en.yml
- spec/features/applicant_page_spec.rb
- spec/features/asylum_and_immigration_spec.rb
- spec/features/result_page_spec.rb
- spec/services/submit_proceedings_service_spec.rb
- spec/support/navigation_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-638)
Added domestic abuse to the matter_type page
This change is to the certificated flow but it only visible when the controlled work flag is enabled, so the original flow remains unchanged.
> EL 638 matter type page certificated

- app/helpers/asylum_support_helper.rb
- app/lib/case_details_section.rb
- app/views/estimate_flow/asylum_support.html.slim
- config/locales/en.yml
- spec/features/asylum_and_immigration_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-705)
needs to be rebased on 696 when that is merged before it is ready for review
> EL-705 add certificated asylum support question

- app/controllers/estimates_controller.rb
- app/views/estimates/_asylum_support_certificated_eligible.html.slim
- app/views/estimates/_asylum_support_controlled_eligible.html.slim
- app/views/estimates/_evidence.html.slim
- app/views/estimates/_limits_table.html.slim
- app/views/estimates/_result_panel_content.html.slim
- app/views/estimates/print.html.slim
- app/views/estimates/show.html.slim
- config/locales/en.yml
- spec/features/asylum_and_immigration_spec.rb
- spec/views/estimates/show.html.slim_spec.rb
[Jira ticket 1](https://dsdmoj.atlassian.net/browse/EL-698)
[Jira ticket 2](https://dsdmoj.atlassian.net/browse/EL-706)
Update the results screens to show different wording in different situations.
As this is all view logic I've used a view spec. This also gets around the fact that some scenarios are unreachable without EL-638 and EL-705
> EL-698 & 706 results screens

- helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-715)
I forgot to remove a commit before merging
> Fix forgotten UAT switch

- README.md
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-729)
Aspirational description of CCQ's test coverage.
> EL-729: Add new test plan to readme

- app/views/estimate_flow/partner_details.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-748)
update content on the partner details page
> EL-748 alternative partner flow

- app/views/estimates/_evidence.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-763)
Fix indentation of bullet points on the evidence screen
> EL-763: Fix indentation

- app/forms/property_form.rb
- app/services/base_cfe_service.rb
- app/services/submit_applicant_service.rb
- app/services/submit_assets_service.rb
- app/services/submit_benefits_service.rb
- app/services/submit_dependants_service.rb
- app/services/submit_employment_income_service.rb
- app/services/submit_irregular_income_service.rb
- app/services/submit_partner_service.rb
- app/services/submit_proceedings_service.rb
- app/services/submit_regular_transactions_service.rb
- app/services/submit_vehicle_service.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-764)
SubmitXServices now use StepsHelper's knowledge to reduce logic duplication (so that if the flow changes we don't have to update the services)
> EL-764: SubmitServices defer to StepsHelper

- README.md
Whilst onboarding I noticed a few steps that might be useful to add to the README. These have been added in this PR.
> [xxx] Update README

- helm_deploy/laa-estimate-eligibility/values/production.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-774)
We need to switch on the Controlled work flow in production. This PR enables the controlled work feature flag.
> [EL-774] Enable controlled work on production

- app/services/cfe_service.rb
- spec/features/level_of_help_page_spec.rb
https://dsdmoj.atlassian.net/browse/EL-723
> EL-723 rename level_of_representation as level_of_help

- README.md
Have updated the set-up instructions in README.md file and added relevant links, where there weren't any previously. 
- Tests and rubocop should be passing - **should pass**
- Branch is generally up to date with main Github - definitely no conflicts - **yes**
- No unnecessary whitespace changes. These make diffs harder to read and conflicts more likely. - **N/A**
- PR description says *what* changed and *why*, with a link to the JIRA story. - **no JIRA ticket** 
- Diff has been checked for unexpected changes being included. - **checked**
- Commit messages say why the change was made. - **yes**
> Update to links & set-up instructions in README.md

- app/models/calculation_result.rb
- app/views/estimates/_capital_table.html.slim
- app/views/estimates/_outgoings_table.html.slim
- config/locales/en.yml
- spec/factories/api_results.rb
- spec/features/result_page_spec.rb
- spec/models/calculation_result_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-753)
Update the results page with new order, separate 'household outgoings' section and up to two vehicles sections
> EL-753: Alt partner results page

- app/views/estimate_flow/level_of_help.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-789)
We haven't enabled the Asylum and Immigration flow yet but we display a bullet point about it on the Level of Help page. This caused some user confusion. Hide this bullet unless the feature flag for the asylum and immigration flow is enabled.
> [EL 789] Show bullet conditionally for Immigration and Asylum

- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-775)
Updated partner question content
> EL-775: Updated partner content

- app/views/benefits/edit.html.slim
- app/views/benefits/new.html.slim
- app/views/estimate_flow/applicant.html.slim
- app/views/estimate_flow/benefits.html.slim
- app/views/estimate_flow/forms/_assets.html.slim
- app/views/estimate_flow/forms/_dependant_details.html.slim
- app/views/estimate_flow/forms/_employment.html.slim
- app/views/estimate_flow/forms/_other_income.html.slim
- app/views/estimate_flow/forms/_outgoings.html.slim
- app/views/estimate_flow/forms/_property.html.slim
- app/views/estimate_flow/forms/_property_entry.html.slim
- app/views/estimate_flow/forms/_vehicle.html.slim
- app/views/estimate_flow/forms/_vehicle_details.html.slim
- app/views/estimate_flow/partner_benefits.html.slim
- app/views/partner_benefits/edit.html.slim
- app/views/partner_benefits/new.html.slim
- app/views/shared/_heading.html.slim
- config/locales/en.yml
- spec/features/benefits_spec.rb
- spec/features/other_income_page_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-769)
Tweak content for alt partner flow
> EL-769: Content changes

- app/helpers/results_helper.rb
- app/models/calculation_result.rb
- app/views/estimates/_capital_table.html.slim
- app/views/estimates/_property_table.html.slim
- config/locales/en.yml
- spec/factories/api_results.rb
- spec/features/result_page_spec.rb
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/records_every_step_of_the_journey_in_analytics_events.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_client_income_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_capital_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Client_accordions/shows_the_outgoings_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_client_income_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_capital_section.yml
- spec/fixtures/vcr_cassettes/Results_Page/Partner_sections_accordions/shows_the_outgoings_section.yml
- spec/models/calculation_result_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-762)
Update property tables as per ticket
> EL-762: Property tables have SMOD and % owned

- app/views/estimate_flow/matter_type.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-733)
Add new content for matter type screen for controlled work.
> EL-733: Controlled matter type content

- app/lib/check_answers_fields.yml
- app/services/check_answers/vehicle_section.rb
- app/views/estimates/_check_answers_table.html.slim
- config/locales/en.yml
- spec/features/assets_page_spec.rb
- spec/features/check_answers_page_spec.rb
- spec/spec_helper.rb
reorder the sections on check answers page for alt partner flow
> EL 752 Check answers page order

- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-667)
Updated feedback SurveyMonkey link in 'en.yml'. No associated tests with this. 
> EL-677 Updated feedback survey link in 'en.yml'

- app/lib/check_answers_fields.yml
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-808)
Changes to content and question order on the 'Check Your Answers' screen to align with content and question order on associated question screens.  
> EL-808 Question order & content change on answers screen

- helm_deploy/laa-estimate-eligibility/values/staging.yaml
Turns on the A&I feature on staging for business testing purposes
> enable A&I feature flag on staging for business testing

- app/services/metrics_service.rb
- spec/services/metrics_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-766)
> EL-766 completion metrics

- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/change-logs.scss
- app/helpers/banner_helper.rb
- app/javascript/application.js
- app/javascript/change-logs.js
- app/models/change_logs.rb
- app/views/change_logs/_banner.html.slim
- app/views/change_logs/_log_item.html.slim
- app/views/change_logs/banner_texts/_dependant_allowance.html.slim
- app/views/change_logs/history_texts/_dependant_allowance.html.slim
- app/views/start/index.html.slim
- config/locales/en.yml
- package.json
- spec/views/start_page/change_logs_spec.rb
- yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-813)
Add logic to show change log banners and history items on the home page, and a specific "dependant allowance" change log highlighting the changes in allowances from 10 April 2023.
> EL-813: Add change log logic

- app/services/metrics_service.rb
- spec/services/metrics_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-766)
- The original PR for EL-766 didn't provide separate controlled/certificated values
- Also, it provided the mean figure, which is heavily skewed by outliers, so we are now switching to the mode.
> EL-766: Completion time by level of help and using mode

- app/views/estimate_flow/level_of_help.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-821)
Added mental health guidance link to level of help screen.
> EL-821: Add mental health guidance

- helm_deploy/laa-estimate-eligibility/values/staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-825)
We need to switch over to the new CFE civil platform. This PR adds the new CFE-Civil staging host to CCQ's staging environment. We will have to merge this work in order to test on our staging environment. 
Before we merge this, we are going to check that CFE Civil UAT works successfully with the CCQ UAT env. Once we are happy, that piece of work will then be merged in, before this one.
Test cases: https://docs.google.com/spreadsheets/d/1tDqIoe7Gwk-X90R_-rv6V5p-vBqC8I-HpiqqeaFGGcw/
I'll do UAT after we merge this by hitting all the endpoints with lots of data and make sure nothing falls over.
- Branch is generally up to date with main Github - definitely …
> [EL-825] Update to CFE Civil staging

- README.md
- app/views/estimate_flow/matter_type.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-832)
Business testing has thrown up some suggestions as to how we can make the 'Which type of matter is this?' screen help text clearer for users and more accurate in terms of the rules.
Have also updated Readme.md file to help with setting up, your local development environment, if not already configured. 
- Commit messages say why the change was …
> EL-832: Controlled work - Changes to content on 'Which type of matter is this?' screen

- helm_deploy/laa-estimate-eligibility/values/production.yaml
Enable the Asylum and Immigration feature flag for production
> release asylum & immigration feature

- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-830)
New help text for the student loan income question.
> EL-830: Copy update for student finance

- app/lib/feature_flags.rb
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-842)
New FF
> EL-842: Add SAG feature flag

- app/forms/applicant_form.rb
- app/helpers/applicant_helper.rb
- app/lib/case_details_section.rb
- app/lib/check_answers_fields.yml
- app/lib/feature_flags.rb
- app/models/check.rb
- app/services/cfe/submit_proceedings_service.rb
- app/views/estimate_flow/applicant.html.slim
- app/views/estimate_flow/level_of_help.html.slim
- app/views/start/index.html.slim
- config/locales/en.yml
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
- spec/end_to_end/without_partner_spec.rb
- spec/factories/session.rb
- spec/features/number_fields_spec.rb
- spec/flows/asylum_and_immigration_flow_spec.rb
- spec/flows/certificated_non_passported_spec.rb
- spec/flows/certificated_passporting_spec.rb
- spec/flows/check_answers_flow_spec.rb
- spec/flows/controlled_work_spec.rb
- spec/forms/applicant_form_spec.rb
- spec/rails_helper.rb
- spec/services/cfe/submit_applicant_service_spec.rb
- spec/services/cfe/submit_proceedings_service_spec.rb
- spec/support/flow_helpers.rb
- spec/views/check_answers_page/client_content/special_client_types/asylum_and_immigration_spec.rb
- spec/views/results_page/asylum_and_immigration_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-839)
Remove A&I feature flag (and now-obsolete `legacy_proceeding_type`)
> EL-839: Remove A&I feature flag

- Gemfile
- Gemfile.lock
- README.md
- config/blazer.yml
- config/routes.rb
- db/migrate/20230426103352_install_blazer.rb
- db/migrate/20230426104843_add_blazer_permissions.rb
- db/schema.rb
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-851)
Add blazer and set appropriate permissions
This mounts Blazer at a new `/data` URL. Access is granted via HTTP Basic Auth, with the password set as a K8s secret (and all K8s secrets are backed up in 1Password, so the password is visible to users there).
Blazer accesses the database using its own username and password (again stored as a K8s secret), and its user account has read-only permissions, so that `/data` can't be used by accident/malice to corrupt or destroy data.
- PR …
> EL-851: Blazer

- app/views/change_logs/_banner.html.slim
- app/views/privacies/show.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-674)
updated privacy policy
updated changelog
TO DO:
- confirm the text of the changelog (not detailed on the ticket)
- update go live date (privacy policy says updated on 11th april but we cant expect to enforce it from that date of it was not published on that date)
> EL-674 update the privacy policy and changelog

- app/controllers/feature_flags_controller.rb
- app/lib/feature_flags.rb
- app/views/feature_flags/index.html.slim
- config/locales/en.yml
- config/routes.rb
- spec/features/feature_flags_spec.rb
- spec/models/feature_flags_spec.rb
- spec/system/accessibility_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-820)
New endpoint that allows us to see at a glance which feature flags are enabled.
> EL-820: Feature flags endpoint

- app/helpers/matter_type_helper.rb
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-857)
Redundant link removed
> EL-857: Remove redundant link

- .circleci/config.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-325)
Get Slack notifications when CI fails
This should flag up if deployment steps fail on any branch, and if standard steps like linters and tests fail when a branch is merged to main.
> EL-325: slack ci integration

- helm_deploy/laa-estimate-eligibility/templates/ingress.yaml
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-727)
Enable modsec to detect but not act on security issues.
> EL-727: Re-enable mod-sec with detection only

- app/views/estimate_flow/applicant.html.slim
- spec/forms/applicant_form_spec.rb
- spec/rails_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-862)
Hide the inaccurate hint text if the flow is altered.
> EL-862: Hide hint if feature flag enabled

- app/forms/client_property_entry_form.rb
- app/forms/partner_property_entry_form.rb
- app/forms/property_form.rb
- app/lib/steps/capital_section.rb
- app/lib/steps/helper.rb
- app/lib/steps/partner_capital_section.rb
- app/lib/steps/property_section.rb
- app/services/cfe/assets_payload_service.rb
- app/views/estimate_flow/household_flow/_property.html.slim
- app/views/estimate_flow/household_flow/_property_entry.html.slim
- app/views/estimate_flow/non_household_flow/_partner_property.html.slim
- app/views/estimate_flow/non_household_flow/_partner_property_entry.html.slim
- app/views/estimate_flow/non_household_flow/_property.html.slim
- app/views/estimate_flow/non_household_flow/_property_entry.html.slim
- app/views/estimate_flow/non_household_flow/forms/_property.html.slim
- app/views/estimate_flow/non_household_flow/forms/_property_entry.html.slim
- app/views/estimate_flow/partner_property.html.slim
- app/views/estimate_flow/partner_property_entry.html.slim
- app/views/estimate_flow/property.html.slim
- app/views/estimate_flow/property_entry.html.slim
- config/locales/en.yml
- spec/flows/household_flow_spec.rb
- spec/forms/property_entry_form_spec.rb
- spec/support/flow_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-852)
For the new household flow we now ask slightly different property questions
> EL-852: New household property questions

- app/controllers/flow/handler.rb
- app/forms/partner_additional_property_details_form.rb
- app/forms/partner_additional_property_form.rb
- app/lib/steps/logic.rb
- app/lib/steps/property_section.rb
- app/services/cfe/partner_payload_service.rb
- app/services/check_answers/section_id_finder.rb
- app/views/estimate_flow/partner_additional_property.html.slim
- app/views/estimate_flow/partner_additional_property_details.html.slim
- config/locales/en.yml
- spec/flows/household_flow_spec.rb
- spec/forms/partner_additional_property_details_form_spec.rb
- spec/forms/partner_additional_property_form_spec.rb
- spec/models/steps/logic_spec.rb
- spec/services/cfe/partner_payload_service_spec.rb
- spec/support/flow_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-867)
Add forms for partner additional properties
> EL-867: Partner additional property

- app/views/layouts/print_application.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-905)
Add the beta banner to the print layout
> EL-905: Beta banner on print and download

- app/forms/base_add_another_form.rb
- app/forms/benefit_details_form.rb
- app/forms/vehicles_details_form.rb
- app/models/check.rb
- app/models/controlled_work_document_content.rb
- app/services/journey_logger_service.rb
- spec/models/check_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-894)
The new household flow puts "is SMOD" flag in unexpected places in the session
> EL-894: Detect SMOD assets more comprehensively

- app/models/completed_user_journey.rb
- app/services/journey_logger_service.rb
- app/services/metrics/from_completed_journeys_service.rb
- db/migrate/20230518104144_add_asylum_support_to_completed_user_journeys.rb
- db/schema.rb
- spec/services/journey_logger_service_spec.rb
- spec/services/metrics/from_completed_journeys_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-895)
Start tracking if checks involve asylum support
> EL-895: Asylum support analytics

- app/assets/stylesheets/application.sass.scss
- app/assets/stylesheets/change-links.scss
- app/lib/check_answers_fields.yml
- app/lib/steps/case_details_section.rb
- app/services/check_answers/section_lister_service.rb
- app/views/estimates/_check_answer.html.slim
- app/views/estimates/_check_answers_table.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-887)
Rework change link alignment
> EL-887: Rework change link alignment

- app/lib/check_answers_fields.yml
- app/lib/steps/property_section.rb
- app/services/check_answers/section_lister_service.rb
- app/views/estimates/_check_answers_table.html.slim
- app/views/estimates/_money_and_frequency_check_answer.slim
- app/views/estimates/_money_check_answer.html.slim
- config/locales/en.yml
- spec/views/check_answers_page/client_content/assets_spec.rb
- spec/views/check_answers_page/client_content/housing_benefit_spec.rb
- spec/views/check_answers_page/client_content/other_income_spec.rb
- spec/views/check_answers_page/client_content/outgoings_spec.rb
- spec/views/check_answers_page/non_household_flow/client_content/other_income_spec.rb
- spec/views/check_answers_page/non_household_flow/client_content/outgoings_spec.rb
- spec/views/check_answers_page/non_household_flow/partner_content/other_income_spec.rb
- spec/views/check_answers_page/non_household_flow/partner_content/outgoings_spec.rb
- spec/views/check_answers_page/partner_content/other_income_spec.rb
- spec/views/check_answers_page/partner_content/outgoings_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-890)
Wording changes for check answers screen for when there is no partner
> EL-890: client-only check answers

- spec/end_to_end/other_income_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-912)
Added test assertions to both the certificated and controlled contexts, to test that CCQ renders in response to its interaction with CFE based on the data submitted.
Assertions are limited to the “other income” part of the results page.
> EL-912: 'other income' integration test assertions 

- app/views/estimate_flow/forms/_benefit_details.html.slim
- app/views/estimate_flow/forms/_employment.html.slim
- app/views/estimate_flow/forms/_other_income.html.slim
- app/views/estimate_flow/forms/_outgoings.html.slim
- app/views/estimate_flow/household_flow/_dependant_details.html.slim
- app/views/estimate_flow/household_flow/_partner_assets.html.slim
- app/views/estimate_flow/household_flow/_partner_details.html.slim
- app/views/estimate_flow/household_flow/_property.html.slim
- app/views/estimate_flow/household_flow/_property_entry.html.slim
- app/views/estimate_flow/household_flow/_vehicle.html.slim
- app/views/estimate_flow/household_flow/forms/_assets.html.slim
- app/views/estimate_flow/housing_costs.html.slim
- app/views/estimate_flow/mortgage_or_loan_payment.html.slim
- app/views/estimate_flow/partner_additional_property.html.slim
- app/views/estimate_flow/partner_additional_property_details.html.slim
- app/views/estimate_flow/partner_benefit_details.html.slim
- app/views/estimate_flow/partner_benefits.html.slim
- app/views/estimate_flow/partner_employment.html.slim
- app/views/estimate_flow/partner_other_income.html.slim
- app/views/estimate_flow/partner_outgoings.html.slim
- app/views/estimate_flow/vehicles_details.html.slim
- app/views/shared/_heading.html.slim
- app/views/shared/_household_tag.html.slim
- app/views/shared/_partner_tag.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-918)
Add tags to household and partner questions in the household flow if there is a partner
> EL-918: tags

- app/views/estimate_flow/applicant.html.slim
- app/views/estimate_flow/benefits.html.slim
- app/views/estimate_flow/forms/_benefit_details.html.slim
- app/views/estimate_flow/forms/_employment.html.slim
- app/views/estimate_flow/forms/_other_income.html.slim
- app/views/estimate_flow/forms/_outgoings.html.slim
- app/views/estimate_flow/household_flow/forms/_assets.html.slim
- app/views/estimate_flow/partner_benefits.html.slim
- config/locales/en.yml
- spec/forms/benefits_form_spec.rb
- spec/forms/partner_benefits_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-916)
Wording tweaks and span removals
> EL-915: Clean-up

- app/helpers/employment_helper.rb
- app/views/estimate_flow/employment.html.slim
- app/views/estimate_flow/forms/_employment.html.slim
- app/views/estimate_flow/partner_employment.html.slim
- config/locales/en.yml
- spec/forms/employment_form_spec.rb
- spec/forms/partner_employment_form_spec.rb
[Jira ticket 1](https://dsdmoj.atlassian.net/browse/EL-899)
[Jira ticket 2](https://dsdmoj.atlassian.net/browse/EL-900)
Add special applicant group content to pay pages
> EL-899 & EL-900: special applicant pay pages

- Dockerfile
- app/lib/cfe_connection.rb
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
- spec/services/cfe_connection_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-930)
Send a user agent header to CFE on every request
> EL-930: Add a user agent string

- app/controllers/application_controller.rb
- app/controllers/estimates_controller.rb
- app/views/errors/missing_session.html.slim
- config/locales/en.yml
- spec/features/accessing_from_another_device_spec.rb
- spec/forms/controlled_work_document_selection_spec.rb
- spec/forms/level_of_help_form_spec.rb
- spec/forms/partner_employment_form_spec.rb
- spec/forms/partner_housing_benefit_details_form_spec.rb
- spec/forms/partner_housing_benefit_form_spec.rb
- spec/forms/partner_other_income_form_spec.rb
- spec/forms/partner_vehicle_details_form_spec.rb
- spec/forms/partner_vehicle_form_spec.rb
- spec/forms/vehicle_details_form_spec.rb
- spec/forms/vehicle_form_spec.rb
- spec/forms/vehicles_details_form_spec.rb
- spec/support/form_helpers.rb
- spec/system/accessibility_spec.rb
- spec/system/add_another_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-931)
Detect empty sessions and show error page if required
> EL-931: Clean error page

- Gemfile
- app/controllers/instant_sessions_controller.rb
- config/initializers/factory_bot.rb
- config/routes.rb
- spec/factories/session.rb
- spec/features/instant_sessions_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-929)
Add 2 endpoints that pre-populate a valid, maximum-screens, minimum-content session for each level of help.
> EL-929: Instant sessions

- app/views/estimates/_controlled_work_next_steps.html.slim
- app/views/estimates/_evidence.html.slim
- app/views/estimates/print.html.slim
- app/views/estimates/show.html.slim
- config/locales/en.yml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-932)
Content tweaks to include reference to the partner in the 'What happens next' and 'Evidence you might need' sections on the results page for controlled work. 
This change is for controlled work and is not behind the CW feature flag.
> EL-932: Controlled work, results page - content update

- app/views/estimate_flow/household_flow/_property.html.slim
- app/views/estimate_flow/household_flow/forms/_assets.html.slim
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
- spec/forms/assets_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-938)
Add a feature flag check to details components on the client and partner assets partial
Add a spec to check the content is hidden when the flag is disabled
> EL-938 add flag check for SPAG content on assets page

- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-940)
Enable household flow in staging and production
> EL-940 turn on household flow in production

- app/lib/feature_flags.rb
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-958)
Add feature flag for self employed
> EL-958 add self employed feature flag

- app/services/cfe_param_builders/household_flow_regular_transactions.rb
- spec/services/cfe/regular_transactions_payload_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-963)
Fix bug and add tests
> EL-963: Prevent nil regular transaction frequencies

- app/lib/controlled_work_mappings/cw1.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-952)
Fix mapping error
> EL-952: CW1 non-smod property bug

- app/models/controlled_work_document_content.rb
- spec/models/controlled_work_document_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-954)
Do not use "Unknown" if value is unknown
> EL-954: Leave ownership percentage field blank if not calculable

- spec/end_to_end/passporting_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-937)
> EL-937 refactor passporting test

- .dockerignore
- Dockerfile
- app/lib/cfe_connection.rb
- spec/services/cfe_connection_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-936)
Use version file for user agent if available
> EL-936: Use version file to store git commit hash in cloud platform

- app/forms/mortgage_or_loan_payment_form.rb
- config/locales/en.yml
- spec/forms/mortgage_or_loan_payment_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-966)
Mortgage payments can be zero
> EL-966: Allow zero mortgage payments

- app/models/calculation_result.rb
- spec/views/results_page/client_financial_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-964)
Added minus signs where necessary
> EL-964: Fix minus signs on vehicle result summaries

- infrastructure/laa-estimate-financial-eligibility-for-legal-aid-uat/ingress-dashboard.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-886)
Tweak dashboard config
> EL-886: Fix dashboard stacking

- app/views/estimate_flow/level_of_help.html.slim
- app/views/start/index.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-949)
Move mental health content to home page
> EL-949: Mental health content

- app/views/estimate_flow/level_of_help.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-950)
Move content into details components
> EL-950: Level of help copy formatting

- .circleci/config.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-970)
Use single workflow with branch filters for infrastructure, staging and production deploys
> EL-970: DRY up Circle workflows

- .circleci/config.yml
- bin/deploy
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-969)
- Move both types of deploy commands into bash file
- Use single job with parameter to access both types of commands
> EL-969: Simplify deployment config

- app/views/estimates/_evidence.html.slim
- config/locales/en.yml
- spec/views/results_page/types_of_evidence_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-908)
Added flag dependent content to the results pagw
> EL-908 add new content to results page

- app/models/change_logs.rb
- app/views/change_logs/history_texts/_special_applicants.html.slim
- app/views/estimate_flow/applicant.html.slim
- app/views/estimate_flow/partner_details.html.slim
- config/locales/en.yml
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-911)
Add new change log and ensure order is correct
> EL-911: Change log update for special applicants

- app/services/metrics/from_analytics_service.rb
- spec/services/metrics/from_analytics_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-976)
Switch from mode to median for completion times.
> EL-976: Switch from mode to median

- README.md
- app/controllers/feature_flags_controller.rb
- app/lib/feature_flags.rb
- app/models/feature_flag_override.rb
- app/views/feature_flags/edit.html.slim
- app/views/feature_flags/index.html.slim
- config/locales/en.yml
- config/routes.rb
- db/migrate/20230615101849_create_feature_flag_overrides.rb
- db/schema.rb
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
- spec/features/feature_flags_spec.rb
- spec/models/feature_flags_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-967)
Mechanism to override feature flags on UAT
> EL-967: Feature flag overrides

- app/views/layouts/_analytics_head.html.slim
- app/views/layouts/application.html.slim
- app/views/layouts/print_application.html.slim
- config/initializers/content_security_policy.rb
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-960)
- Added a content security policy using nonces
- Every script loaded now uses a nonce
- Configured reporting to Sentry
> EL-960: Add a content security policy

- app/controllers/estimates_controller.rb
- app/services/cfe/applicant_payload_service.rb
- app/services/cfe/assessment_payload_service.rb
- app/services/cfe/assets_payload_service.rb
- app/services/cfe/base_service.rb
- app/services/cfe/benefits_payload_service.rb
- app/services/cfe/dependants_payload_service.rb
- app/services/cfe/employment_income_payload_service.rb
- app/services/cfe/invalid_session_error.rb
- app/services/cfe/irregular_income_payload_service.rb
- app/services/cfe/partner_payload_service.rb
- app/services/cfe/proceedings_payload_service.rb
- app/services/cfe/regular_transactions_payload_service.rb
- app/services/cfe/vehicle_payload_service.rb
- app/services/cfe_param_builders/household_flow_regular_transactions.rb
- app/services/cfe_param_builders/partner_regular_transactions.rb
- app/views/estimates/invalid_session.html.slim
- config/locales/en.yml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
- spec/end_to_end/passporting_spec.rb
- spec/end_to_end/without_partner_spec.rb
- spec/features/invalid_session_spec.rb
- spec/services/cfe/applicant_payload_service_spec.rb
- spec/services/cfe/assets_payload_service_spec.rb
- spec/services/cfe/benefits_payload_service_spec.rb
- spec/services/cfe/dependants_payload_service_spec.rb
- spec/services/cfe/employment_income_payload_service_spec.rb
- spec/services/cfe/irregular_income_payload_service_spec.rb
- spec/services/cfe/partner_payload_service_spec.rb
- spec/services/cfe/regular_transactions_payload_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-973)
Detect invalid sessions
> EL-973: Session checking

- app/forms/partner_income_form.rb
- app/lib/check_answers_fields.yml
- app/lib/steps/partner_section.rb
- app/models/check.rb
- app/models/income_model.rb
- app/services/cfe/partner_payload_service.rb
- app/services/cfe_param_builders/capitals.rb
- app/services/cfe_param_builders/irregular_income.rb
- app/services/check_answers/section_lister_service.rb
- app/views/estimate_flow/_income_section.html.slim
- app/views/estimate_flow/forms/_assets.html.slim
- app/views/estimate_flow/forms/_income.html.slim
- config/locales/en.yml
- spec/end_to_end/self_employed_spec.rb
- spec/factories/session.rb
- spec/flows/self_employment_flow_spec.rb
- spec/forms/partner_assets_form_spec.rb
- spec/forms/partner_income_form_spec.rb
- spec/services/cfe/employment_income_payload_service_spec.rb
- spec/services/cfe/partner_payload_service_spec.rb
- spec/support/flow_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-947)
Add new partner screens to match the client screens
> EL-947: partner income scree

- config/blazer.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1003)
Allowing Blazer to override content security settings as per the [documentation](https://github.com/ankane/blazer/tree/ade703d022bc98c2bd1a1259010daab3043fd102#content-security-policy) 
N/A
> EL-1003: Allow Blazer to override CSP settings

- spec/factories/session.rb
- spec/features/instant_sessions_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1004)
Fix typo
Make sure specs actually check the instant session is valid 
> EL-1004: Fix typo in instant sessions and add spec

- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1010)
Fix copy-paste error
> EL-1010: Incorrect wording on partner additional property screen

- app/models/change_logs.rb
- app/views/change_logs/history_texts/_cw_forms.html.slim
- config/locales/en.yml
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-998)
Switch on ff and add change log
> EL-998: CW form switch-on - No merge before 10 July

- app/controllers/helps_controller.rb
- app/lib/feature_flags.rb
- app/views/helps/show.html.slim
- app/views/layouts/_footer.html.slim
- config/locales/en.yml
- config/routes.rb
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-884)
Add a help page
Put link to it behind a feature flag
> EL-884: Add help page for public beta

- app/views/estimate_flow/additional_property_details.html.slim
- app/views/estimate_flow/partner_additional_property_details.html.slim
- app/views/estimate_flow/property_entry.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-981)
> EL-981: Add more text about valuations.

- config/locales/en.yml
- spec/views/results_page/client_financial_content_spec.rb
- spec/views/results_page/pensioner_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1001)
Update pensioner disregard name
> EL-1001: Update pensioner disregard name

- spec/end_to_end/result_page_variations_spec.rb
- spec/support/flow_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1000)
Add specs that test out some CFE logic, specifically:
- Upper thresholds
- Lower thresholds
- Childcare eligibility
- SMOD disregards
- 60+ disregards
> EL-1000: Add more end-to-end specs

- .circleci/config.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1036)
Tell Jira that the deploy to the environment "Production" is a production deploy, so it can treat it specially
> EL-1036 - Set environment_type of production deploy

- app/helpers/applicant_helper.rb
- app/helpers/assets_helper.rb
- app/helpers/employment_helper.rb
- app/lib/feature_flags.rb
- app/views/estimate_flow/applicant.html.slim
- app/views/estimate_flow/forms/_assets.html.slim
- app/views/estimate_flow/forms/_employment.html.slim
- app/views/estimate_flow/forms/_income.html.slim
- app/views/estimate_flow/partner_details.html.slim
- app/views/estimate_flow/property.html.slim
- app/views/estimates/_evidence.html.slim
- app/views/start/index.html.slim
- config/locales/en.yml
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
- spec/forms/applicant_form_spec.rb
- spec/forms/assets_form_spec.rb
- spec/forms/employment_form_spec.rb
- spec/forms/partner_assets_form_spec.rb
- spec/forms/partner_employment_form_spec.rb
- spec/rails_helper.rb
- spec/views/results_page/types_of_evidence_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1027)
The feature flag is never being switched off, so we're hard-coding it being enabled into the code and removing the flag itself.
> EL-1027: Remove special applicants feature flag

- app/helpers/application_helper.rb
- app/javascript/application.js
> EL-1047: CSP-friendly approach to JS back button

- bin/deploy
- helm_deploy/laa-estimate-eligibility/templates/NOTES.txt
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/templates/ingress.yaml
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1033)
Adjust how we build ingress chart so that we can pass in a secret name for a given host
Pass in a secret name for a new staging host.
> EL-1033: new staging domain

- app/controllers/start_controller.rb
- spec/features/referrers_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1034)
Check for 'ref' params, track and remove
> EL-1034: Track referrers

- app/models/change_logs.rb
- app/views/change_logs/banner_texts/_mtr_phase_1.html.slim
- app/views/change_logs/history_texts/_mtr_phase_1.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1035)
New banner and changelog for MTR phase 1
> EL-1035: Add MTR phase 1 banner and changelog

- README.md
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1020)
Update the readme to highlight the relationship with CFE Civil as per service assessment feedback.
> EL-1020: Update readme to highlight CFE-Civil

- app/views/start/index.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1013)
New content about clients under 18 for MTR phase 1
> EL-1013: Update under-18 content

- app/views/accessibilities/show.html.slim
- config/locales/en.yml
- spec/system/accessibility_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1040)
Improve wording of accessibility statement
Also add missing target/rel attributes of anchors
> EL-1040: Update accessibility statement for clarity

- app/models/change_logs.rb
- app/views/change_logs/history_texts/_self_employed.html.slim
- config/locales/en.yml
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1057)
Switch on feature flag
Add change log
> EL-1057: Switch on self-employed

- app/views/estimate_flow/forms/_assets.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1019)
new hint text on client and partner assets screens
> EL-1019 add new hints for all levels of help

- app/lib/feature_flags.rb
- app/views/estimates/print.html.slim
- app/views/estimates/show.html.slim
- config/locales/en.yml
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
- spec/features/downloads_spec.rb
- spec/flows/controlled_work_documents_spec.rb
- spec/rails_helper.rb
- spec/views/results_page/cw_forms_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1059)
Remove the CW form feature flag
> EL-1059: Remove CW form feature flag

- app/views/change_logs/history_texts/_mtr_phase_1.html.slim
- config/locales/en.yml
- spec/forms/controlled_work_document_selection_spec.rb
- spec/services/guidance_link_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1073)
Remove 'Para 2' wording, as this text was not needed anymore.
Also had to update some tests for full branch coverage. 
> EL-1073: MTR Phase 1 - remove typo

- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1072)
Removed link as links below it are effectively duplicates.
> EL-1072: Remove link

- app/views/estimates/_asylum_support_certificated_eligible.html.slim
- app/views/estimates/_certificated_eligible.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1077)
Highlight that eligible certificated clients don't need to make a contribution
> EL-1077: Bold text

- .circleci/config.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1078)
When we pull CFE image from ECR, use short-lived credentials
> EL-1078: Try ensuring we use short credentials for e2e

- app/assets/stylesheets/add-another.scss
- app/controllers/flow/handler.rb
- app/forms/dependant_income_details_form.rb
- app/forms/dependant_income_form.rb
- app/helpers/dependants_helper.rb
- app/javascript/add-another.js
- app/lib/check_answers_fields.yml
- app/lib/steps/applicant_details_section.rb
- app/lib/steps/logic.rb
- app/models/calculation_result.rb
- app/models/concerns/outgoings_summarisable.rb
- app/models/dependant_income_model.rb
- app/models/income_model.rb
- app/services/cfe/dependants_payload_service.rb
- app/services/cfe_param_builders/dependants.rb
- app/views/estimate_flow/_dependant_income_section.html.slim
- app/views/estimate_flow/dependant_income.html.slim
- app/views/estimate_flow/dependant_income_details.html.slim
- config/locales/en.yml
- spec/end_to_end/without_partner_spec.rb
- spec/forms/dependant_income_details_form_spec.rb
- spec/forms/dependant_income_form_spec.rb
- spec/models/controlled_work_document_content_spec.rb
- spec/models/steps/logic_spec.rb
- spec/services/cfe/dependants_payload_service_spec.rb
- spec/support/flow_helpers.rb
- spec/views/results_page/client_financial_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1049)
Add new dependant income screens and associated CFE payload logic, results page tweaks and check answer updates
> EL-1049: Dependant incomes

- app/helpers/application_helper.rb
- app/views/controlled_work_document_selections/new.html.slim
- app/views/estimates/show.html.slim
- app/views/layouts/_footer.html.slim
- app/views/layouts/application.html.slim
- app/views/shared/_survey_prompt.html.slim
- config/locales/en.layouts.yml
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1082)
Prompt users at the end of their journey to fill out a survey.
> EL-1082: Add end-of-journey survey prompt

- app/views/estimates/check_answers.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1064)
Add new help text about saving answers to check answers screen.
> EL-1064: New help text

- app/services/metrics/for_user_journey_dashboard_service.rb
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
- spec/services/metrics/for_user_journey_dashboard_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1056)
We're now doing a completely different dashboard for user journeys, so need to send very different-looking data accordingly.
> EL-1056: Rework mechanism for restructured user journey dashboard

- app/views/estimate_flow/level_of_help.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1098)
Add hint text to explain what controlled work is.
> EL-1098: Add controlled work hint text

- app/helpers/results_helper.rb
- app/views/estimates/_asylum_support_certificated_eligible.html.slim
- app/views/estimates/_certificated_contribution_required.html.slim
- app/views/estimates/_certificated_eligible.html.slim
- app/views/estimates/_certificated_ineligible.html.slim
- app/views/estimates/_controlled_eligible.html.slim
- app/views/estimates/_controlled_work_next_steps.html.slim
- app/views/estimates/_evidence.html.slim
- app/views/estimates/_income_table.html.slim
- app/views/estimates/_outgoings_table.html.slim
- app/views/estimates/print.html.slim
- app/views/estimates/show.html.slim
- config/locales/en.yml
- spec/features/downloads_spec.rb
- spec/system/accessibility_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1086)
Make the CW form CTA more prominent when present.
> EL-1086: Rework results page for eligible controlled checks

- helm_deploy/laa-estimate-eligibility/values/production.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1065)
- Turn on feature flag
- Allow indexing by search engines
- Start redirecting to the primary domain
> EL-1065: Enable all public beta config

- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1125)
Added a missing 0
> EL-1125: Add missing 0

- .github/actions/delete-uat-release/action.yml
- app/controllers/status_controller.rb
- app/services/health_check_service.rb
- config/routes.rb
- helm_deploy/laa-estimate-eligibility/templates/deployment.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
- spec/requests/statuses_controller_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1115)
separated liveness and readiness checks during deploy process
delete pvc after merge or close PR
> EL-1115 add separate checks for readiness and liveness

- .circleci/config.yml
- app/lib/feature_flags.rb
- app/services/guidance_link_service.rb
- app/views/start/index.html.slim
- config/locales/en.yml
- spec/services/guidance_link_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1106)
remove mtr flags and references and update URL for PDF and guidance links
> EL-1106 MTR phase 1 cleanup

- config/initializers/sentry.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1132)
Update the check to include "health" as well as "status", but also check that those are the whole of the URL, not some longer URL that just includes that word.
> EL-1132: Discount both k8s check endpoints from sentry profiling

- app/controllers/documents_controller.rb
- app/helpers/applicant_helper.rb
- app/helpers/assets_helper.rb
- app/helpers/asylum_support_helper.rb
- app/helpers/build_estimates_helper.rb
- app/helpers/dependants_helper.rb
- app/helpers/employment_helper.rb
- app/helpers/housing_costs_helper.rb
- app/helpers/matter_type_helper.rb
- app/helpers/outgoings_helper.rb
- app/helpers/property_helper.rb
- app/helpers/vehicle_helper.rb
- app/services/guidance_link_service.rb
- app/views/estimate_flow/forms/_assets.html.slim
- app/views/estimate_flow/immigration_or_asylum.html.slim
- app/views/estimate_flow/immigration_or_asylum_type.html.slim
- app/views/estimate_flow/level_of_help.html.slim
- app/views/estimate_flow/matter_type.html.slim
- app/views/estimate_flow/vehicle.html.slim
- app/views/estimates/_legislation_table.html.slim
- app/views/estimates/_limits_table.html.slim
- app/views/shared/_disregarded_benefits_sidebar.html.slim
- app/views/start/index.html.slim
- config/routes.rb
- spec/controllers/documents_controller_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1045)
Intercept all clicks on guidance links so that we can track what document was linked to, from where, on what check.
> EL-1045: Track all clicks on guidance links

- app/helpers/application_helper.rb
- app/lib/feature_flags.rb
- app/views/layouts/_footer.html.slim
- app/views/shared/_heading.html.slim
- config/locales/en.yml
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
- spec/features/help_spec.rb
- spec/rails_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1130)
Removed the public beta feature flag
> EL-1130: Remove public beta feature flag

- app/views/layouts/application.html.slim
- app/views/layouts/print_application.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1131)
Add missing doctype declarations that were causing subtle layout bugs.
> EL-1131: Add missing doctype declarations

- app/controllers/documents_controller.rb
- app/models/analytics_event.rb
- spec/controllers/documents_controller_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1165)
When bots visit this endpoint params are missing. Currently we try to write analytics events but with required attributes missing it blows up. So this changes it to skip the database write if we don't have the right params.
Also I've added an explicit validation to the model layer to mirror the validations in the DB schema to make it clearer that those requirements exist.
- Diff has been checked for …
> EL-1165: Cope with missing params

- .slim-lint.yml
- app/views/layouts/_footer.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1150)
Make footer linter-compliant
> EL-1150: Footer line length

- app/controllers/oauth_redirects_controller.rb
- config/locales/en.yml
- spec/controllers/oauth_redirects_controller_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1151)
Add error case and more graceful handling
> EL-1151: Handle hits to `/subdomain_redirects` without state param

- app/views/results/_limits_table.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1185)
Fix typo and minor refactor
> EL-1185: Gross income limit typo

- app/services/external_link_service.rb
- app/views/start/index.html.slim
- config/locales/en.yml
- spec/controllers/documents_controller_spec.rb
- spec/features/basic_auth_spec.rb
- spec/features/maintenance_mode_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1137)
Add new content to the start page. Also, add a 'related content' sidebar with the public legal aid calculator.
Add link tracking for the public legal aid calculator.
> EL-1137: Start page updates

- app/assets/stylesheets/add-another.scss
- app/javascript/add-another.js
- app/views/question_flow/dependant_income_details.html.slim
- app/views/question_flow/forms/_additional_property_details.html.slim
- app/views/question_flow/forms/_assets.html.slim
- app/views/question_flow/forms/_benefit_details.html.slim
- app/views/question_flow/forms/_income.html.slim
- app/views/question_flow/vehicles_details.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1138)
Show a little widget when an instance is removed to make it clearer that something has been taken away.
> EL-1138: Show visual feedback when removing an 'add-another' instance

- app/controllers/instant_sessions_controller.rb
- config/initializers/content_security_policy.rb
- spec/features/instant_sessions_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1208)
404 instead of 500 on typo on instant session URL
> EL-1208: Instant 404

- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1218)
missing an `laa-` in the ingress name for the new NS
> EL-1218 fix ingress name

- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
Reverts ministryofjustice/laa-estimate-financial-eligibility-for-legal-aid#1060
> Revert "EL-1214 switch staging ingress hosts"

- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1238)
First PR - turn on maintenance mode
there are 2 further PRs for this ticket:
Part B: https://github.com/ministryofjustice/laa-estimate-financial-eligibility-for-legal-aid/pull/1064
Part C: https://github.com/ministryofjustice/laa-estimate-financial-eligibility-for-legal-aid/pull/1065
> EL-1238 Part A: turn on UAT maintenance mode

- .circleci/config.yml
- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1238)
Turn off maintenance mode and revert circleci config
This is the 3rd PR and should not be merged until Part B has been merged with main and has fully deployed
> EL-1238 Part C: switch off maintenace mode

- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
> EL-1238: Step 1 enable maintenance mode

- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
> El 1238: Step 2 swap hostnames

- .circleci/config.yml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1242)
> EL-1242: Step two: swap hosts over

- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1242)
> EL-1242: Step three: disable maintenance mode

- .circleci/config.yml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
Reverts ministryofjustice/laa-estimate-financial-eligibility-for-legal-aid#1076
Mas and I are re-testing the staging swap process
> Revert EL-1242: Step two: swap hosts over

- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1242)
> EL-1242 - Step 1 - Part 1

- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1242)
> EL-1242 - Step 2 - Part 3

- app/lib/feature_flags.rb
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
- spec/rails_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1267)
- Creation of a new feature flag for the new ‘End of Journey’ flow.
- As per the `Readme.md` and [EL-961](https://github.com/ministryofjustice/laa-estimate-financial-eligibility-for-legal-aid/pull/770), I've chosen for this feature flag to be based on the `session_data` as the changes in this epic are not policy specific. 
- Commit messages say …
> EL-1267: End of Journey - feature flag

- config/locales/en.yml
- spec/views/check_answers_page/client_content/special_client_types/asylum_and_immigration_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1259)
- Change to .yml file where values are picked up from
- Update to test's to make test correct ones a displaying
- Apologies I missed this when doing [EL-1161](https://github.com/ministryofjustice/laa-estimate-financial-eligibility-for-legal-aid/pull/981)
[EL-161]: …
> EL-1259: Incorrect check answers text

- app/lib/check_answers_fields.yml
- spec/views/check_answers_page/client_content/assets_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1244)
Re-add missing disputed asset tags
> EL-1244: Missing disputed asset tags

- app/lib/feature_flags.rb
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
- helm_deploy/laa-estimate-eligibility/values/production.yaml
- helm_deploy/laa-estimate-eligibility/values/staging.yaml
- helm_deploy/laa-estimate-eligibility/values/uat.yaml
- spec/rails_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1247)
I've added this as a session feature flag because when we switch it on, we want checks that were started before it was enabled still to be valid.
> EL-1247: Add feature flag for under-18 questions

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
CFE host for new production was set to point to staging, change to point to CFE production
> update cfe host to prod

- app/views/results/download.html.slim
- app/views/results/show.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1279)
Add text for certificated results heading
> EL-1279: Tweak certificated results wording

- app/controllers/flow/handler.rb
- app/forms/regular_income_form.rb
- app/lib/steps/case_details_section.rb
- app/lib/steps/logic.rb
- app/services/external_link_service.rb
- app/views/question_flow/regular_income.html.slim
- config/locales/en.yml
- spec/flows/under_eighteen_flow_spec.rb
- spec/forms/regular_income_form_spec.rb
- spec/support/flow_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1251)
Add new regular income screen for u-18s.
> EL-1251: Regular income screen

- app/services/external_link_service.rb
- app/views/question_flow/under_18_clr.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1249)
> EL-1249 under18 CLR question

- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1284)
- Change 'means assessment' to 'full means test' on 2 pages
N/A
> EL-1284: Change 'means assessment' to 'full means test'

- app/models/calculation_result.rb
- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
- spec/views/results_page/eligibility_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1285)
updated method to determine if a result has been calculated, instead of checking for pending we check if any of the completed results are included.  This ensures that future CFE changes to incomplete result options do not affect us until we have alternative outcomes for these options.
> EL-1285 Update method to account for new CFE result type

- app/controllers/controlled_work_document_selections_controller.rb
- app/controllers/results_controller.rb
- app/helpers/application_helper.rb
- config/locales/en.yml
- spec/flows/controlled_work_documents_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1286)
Reformat CW download file names
> EL-1286: CW file names

- app/views/results/_certificated_ineligible.html.slim
- app/views/results/_certificated_next_steps.html.slim
- app/views/results/download.html.slim
- app/views/results/show.html.slim
- config/locales/en.yml
- spec/views/results_page/eligibility_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1111)
Adjust content for ineligible certificated results
> EL-1111: Certificated/ineligible results text

- .github/workflows/rubocop.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1287)
To trigger Rubocop from combine-PRs workflow we need to first adjust the Rubocop workflow to allow that sort of triggering.
> EL-1287a: Rubocop workflow can be "dispatched" via API

- app/models/additional_property_model.rb
- spec/system/add_another_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1289)
Fix bug in mortgage validation
> EL-1289: Additional property mortgage validation

- app/javascript/instant-download.js
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1300)
Fix instant-download CSS selector
> EL-1300: Instant downloads mobile safari error

- app/views/question_flow/mortgage_or_loan_payment.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1234)
Add details component to mortgage page
> EL-1234: Add new text to mortgage page

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1294)
turns metabase on for production
> EL-1294 turn metabase on in production

- app/controllers/flow/handler.rb
- app/forms/how_to_aggregate_form.rb
- app/lib/steps/case_details_section.rb
- app/services/external_link_service.rb
- app/views/question_flow/how_to_aggregate.html.slim
- app/views/start/index.html.slim
- config/locales/en.yml
- spec/flows/under_eighteen_flow_spec.rb
- spec/rails_helper.rb
- spec/support/flow_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1288)
Add a new screen with a blank form object so we can show the appropriate guidance text.
The `--headless=new` thing is because on my machine, headless chrome is no longer providing browser logs without it (h/t https://github.com/SeleniumHQ/selenium/issues/13112 for solving this)
> EL-1288: Means aggregation

- app/lib/feature_flags.rb
- app/models/controlled_work_document_selection.rb
- app/views/controlled_work_document_selections/new.html.slim
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
- spec/flows/controlled_work_documents_spec.rb
- spec/forms/controlled_work_document_selection_spec.rb
- spec/rails_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1302)
Remove the Welsh CW form feature flag.
> EL-1302: Remove Welsh CW form feature flag

- app/models/controlled_work_document_content.rb
- app/views/question_flow/how_to_aggregate.html.slim
- spec/services/controlled_work_document_value_mapping_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1311)
Some CW fields were being filled in even when irrelevant when an u18 client was exempt from a means test.
> EL-1311: Skip irrelevant CW fields when u18

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
> Enable u18 on staging and production

- app/forms/other_income_form.rb
- app/lib/check_answers_fields.yml
- app/lib/check_answers_fields_old_flow.yml
- app/lib/feature_flags.rb
- app/models/check.rb
- app/services/cfe_param_builders/irregular_income.rb
- app/services/cfe_param_builders/regular_transactions.rb
- app/services/check_answers/section_lister_service.rb
- app/services/childcare_eligibility_service.rb
- app/views/checks/_check_answers_table.html.slim
- app/views/checks/_money_and_frequency_check_answer.slim
- app/views/checks/_money_check_answer.html.slim
- app/views/question_flow/forms/_other_income.html.slim
- config/locales/en.yml
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
- spec/end_to_end/other_income_spec.rb
- spec/forms/other_income_form_spec.rb
- spec/rails_helper.rb
- spec/services/childcare_eligibility_service_spec.rb
- spec/views/check_answers_page/client_content/outgoings_spec.rb
- spec/views/check_answers_page/partner_content/outgoings_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1305)
- Add conditional reveals feature flag (this will be off everywhere by default, only switched on in certain specific UAT environments
- When it's switched on, other income and partner other income use conditional reveals
- And check answers is updated appropriately
- And information is sent to CFE appropriately
- Commit messages say why the …
> EL-1304: Conditional reveals on other income

- config/locales/en.yml
- spec/end_to_end/result_page_variations_spec.rb
- spec/end_to_end/without_partner_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-980)
- Update to text in 'blue box' on results page, when it's a certificated check and contributions are required
N/A
> EL-980: Certificated Results page - contributions content update

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- lib/tasks/jobs/simplecov_coverage.rake
- spec/spec_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1292)
add parallelism to circleci for running specs
remove 100% coverage requirement on circle
store the test results
add new job to collate results
add new rake task to collate results and ensure 100% coverage
> EL-1292: In CircleCi, run tests in parallel - WIP

- .github/workflows/browser_tools_docker_image.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1320)
- Create `browser_tools_docker_image.yml`
- This is part 1 of 2
> EL-1320: Part 1 - Speed up the run_specs CI job, by extending image into new published docker image

- public/maintenance.html
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1273)
Update content for maintenance period
Turned on maintenance mode in UAT to check content in UAT, this will be reverted before merge
> EL-1273 update maintenance page

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1327)
Turn on maintenance mode in PROD before DB upgrade
> EL-1327 PR 1 - Turn on maintenance mode for PROD

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
> turn off maintenance mode

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1327)
turn on maintenance mode foer DB upgrade
> EL-1327 turn on maintenance mode for PROD

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1327)
turns maintenance mode off after DB upgrade
> EL-1327 B turn maintenance off in prod

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
release the outgoings flow changes to production
> EL-1357 turn on outgoings flow feature

- app/controllers/forms_controller.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1383)
Error in back link detailed here:
https://mojdt.slack.com/archives/C02BKRV26KS/p1708698718999919
this wad introduced when we refactored the back button
> EL-1383 update assigns the previous step to fix back link bug

- app/views/question_flow/applicant.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1342)
Change content on applicant page to have summary reveals rather than large amounts of static text 
> EL-1342 tidy up content on applicant page

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- public/maintenance.html
Turn on maintenance mode for production.
This PR will be merged at 7am Thursday prior to the DB upgrade
> EL-1396 CFE DB Upgrade: Enable maintenance mode in Production

- spec/features/invalid_session_spec.rb
- spec/rails_helper.rb
- spec/services/analytics_service_spec.rb
- spec/services/choice_analytics_service_spec.rb
- spec/services/error_service_spec.rb
- spec/services/journey_log_update_service_spec.rb
- spec/services/journey_logger_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1403)
Add defensive checks to all tests (except those specifically marked) so that errors don't happen silently
> El1403 disable error catch for tests

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1353)
Convert cron schedule to directly running job in github
> El 1353 tag docker images with branch

- .circleci/config.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1353)
Need to use main branch for circle tests, otherwise all builds fail
> use main branch image for running circle tests

- .circleci/config.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
No Ticket
Puppeteer still needs to be tweaked manually rather than upgraded with dependabot
> Puppeteer 2250

- app/controllers/instant_sessions_controller.rb
- app/forms/other_income_form.rb
- config/locales/en.yml
- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
- spec/factories/session.rb
- spec/features/instant_sessions_spec.rb
- spec/forms/other_income_form_spec.rb
- spec/forms/partner_other_income_form_spec.rb
- spec/forms/partner_outgoings_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1365)
> EL-1365: Switch on client/partner other income and outgoings conditional reveals

- app/views/checks/_check_answer.html.slim
- app/views/checks/_check_answers_table.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1407)
Change answers links with aria-labels
> EL-1407 change answers links with aria-label

- app/views/question_flow/applicant.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1402)
Move error message content
> EL-1402 move applicant error message

- spec/end_to_end/with_partner_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1404)
Fix end 2 end tests after uprating changes to not depend on precise values from CFE
> EL-1404 remove dependance on precise partner allowance figure

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1479)
Release early eligibility to production
To be merged Tuesday 16th April 2024 8am (ish)
> EL-1479 switch early eligibility feature on in production

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
No ticket
Puppeteer upgrade to 22.6.5
> Puppeteer 22.6.5 upgrade

- app/forms/other_income_form.rb
- app/forms/outgoings_form.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1511)
Removed too much code in the conditional reveals ticket, ended up removing the frequency validation. This puts it back in,
> EL-1511 put validation back in, removed in error

- app/lib/feature_flags.rb
No ticket
Add defaults for feature flags, so some can be switched on by default
As per discussion in dev time 9/5/24
> Add default values to feature flags

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
No ticket
Puppeteer 22.8.2
Upgrade puppeteer once more
> Puppeteer 2282

- package.json
- yarn.lock
Reverts ministryofjustice/laa-check-client-qualifies#1378
> Revert "Bump the combined-dependencies group across 1 directory with 4 updates"

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
No ticket
Upgrade to puppeteer 22.9.0
Yet another puppeteer upgrade
> Puppeteer 22.9.0

- app/views/question_flow/forms/_other_income.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1522)
- Changes to content on the Client and Partner Other Income pages to handle the new mandatory/discretionary disregards that are being implemented as part of 'MTR Phase 2 - accelerated changes' for both Controlled and Certificated journeys.
- Not behind feature flag.
> EL-1522: Client and Partner Other Income pages content update

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
> update puppeteer to 22.10

- app/helpers/checks_helper.rb
- app/helpers/property_helper.rb
- app/views/checks/_check_answers_table.html.slim
- app/views/question_flow/mortgage_or_loan_payment.html.slim
- config/locales/en.yml
- spec/forms/mortgage_or_loan_payment_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1518)
MTR accelerated changes mortgage or loan screen
Based on EL-1517 as varying change answers screen content is a bit trickly 
> El 1518 mortgage or loan

- app/helpers/checks_helper.rb
- app/helpers/property_helper.rb
- app/views/checks/_check_answers_table.html.slim
- app/views/question_flow/property_entry.html.slim
- config/locales/en.yml
- spec/end_to_end/without_partner_spec.rb
- spec/forms/property_entry_form_spec.rb
- spec/views/results_page/client_financial_content_spec.rb
- spec/views/results_page/partially_owned_property_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1517)
Content for MTR accelerated property entry screen
> El 1517 accel mtr property entry

- app/helpers/property_helper.rb
- app/views/question_flow/property.html.slim
- config/locales/en.yml
- spec/forms/property_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1516)
Property page for Accelerated MTR
> El 1516 Property page for Accelerated MTR

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
turn the new feature on n staging and production
> turn on conditional reveals

- app/views/question_flow/forms/_benefit_details.html.slim
- app/views/question_flow/forms/_benefits.html.slim
- app/views/shared/_disregarded_benefits_details.html.slim
- config/locales/en.yml
- spec/forms/benefits_form_spec.rb
- spec/views/check_answers_page/client_content/other_benefits_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1519)
Replace benefits list with guidance
> EL-1519 Replace benefits content list with guidance

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
update puppeteer references and docker image
> update puppeteer version

- README.md
No ticket
Update readme to cover  chromedriver upgrade process
> Add note about warnings when updating chromedriver

- app/services/external_link_service.rb
- app/views/shared/_related_without_new_tab.html.slim
- app/views/start/index.html.slim
- config/locales/en.yml
- spec/features/basic_auth_spec.rb
- spec/features/maintenance_mode_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1427)
Change start page content to simplify and improve readability
> EL-1427 New content on start page

- .github/actions/delete-uat-release/action.yml
Fixes the trigger for calling the github action
> fix the GA delete action

- .github/actions/delete-uat-release/action.yml
Reverts ministryofjustice/laa-check-client-qualifies#1457
> Revert "fix the GA delete action"

- app/views/privacies/show.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1625)
Update text of privacy policy in line with the ticket
Date changed
> EL-1625 portal privacy text

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
Update puppeteer to latest version
> update puppeteer: part deux

- app/services/old_data_removal_service.rb
- spec/factories/providers.rb
- spec/services/old_data_removal_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1632)
Delete old portal usernames for data protection purposes
> EL-1632 delete portal users after 1 week

- app/lib/check_answers_fields.yml
- app/lib/check_answers_fields_legacy.yml
- app/services/check_answers/section_lister_service.rb
- app/views/checks/_boolean_money_with_frequency.slim
- app/views/checks/_check_answers_table.html.slim
- app/views/checks/_money_and_frequency_check_answer.slim
- app/views/checks/_money_with_frequency.slim
- app/views/checks/_optional_money_check_answer.html.slim
- app/views/checks/_optional_money_with_frequency.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1572)
EL-1572's spike has uncovered a handful of simplifications to the mainline codebase. These are contained here to keep them apart from the spike itself
> EL-1572 Tidy ups

- app/lib/feature_flags.rb
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
- spec/rails_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1583)
- added a  shared ownership feature flag.
- none
> EL-1583: Shared Ownership feature flag

- app/lib/laa_portal/saml_strategy.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1660)
We are trying to investigate strange occasional errors in our SAML code, where the logout request step fails.
This PR adds error logging to help us diagnose the problem when it actually occurs by sending it direct to Sentry
n/a
> EL-1660 Add error logging for SAML Logout request error

- spec/flows/certificated_passporting_spec.rb
- spec/flows/controlled_work_spec.rb
- spec/flows/under_eighteen_flow_spec.rb
- spec/forms/benefit_details_form_spec.rb
- spec/forms/controlled_legal_representation_form_spec.rb
- spec/forms/employment_status_form_spec.rb
- spec/forms/other_income_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1645)
Improve check answers display test coverage prior to refactor of check answers code
> EL-1645 improve check answers coverage

- Gemfile
- Gemfile.lock
- app/models/admin.rb
- app/models/analytics_event.rb
- app/models/banner.rb
- app/models/change_log.rb
- app/models/completed_user_journey.rb
- app/models/feature_flag_override.rb
- app/models/freetext_feedback.rb
- app/models/issue.rb
- app/models/issue_update.rb
- app/models/provider.rb
- app/models/satisfaction_feedback.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1630)
Convert explicit model attributes into annotations
> El 1630 model annotation gem

- app/controllers/change_answers_controller.rb
- app/controllers/question_flow_controller.rb
- app/lib/steps/helper.rb
- app/lib/steps/logic.rb
- app/lib/steps/non_financial_section.rb
- app/models/cfe_result.rb
- app/models/check.rb
- spec/flows/early_result_change_answers_flow_spec.rb
- spec/support/flow_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1668)
Refactor change answers controller to look for consistency in the answers data and react accordingly
> EL-1668 Refactor change answers controller

- Gemfile
- Gemfile.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1691)
add gemfile rexml constraint to prevent accidental downgrade
> EL-1691 add gemfile rexml constraint to prevent accidental downgrade

- app/controllers/providers/omniauth_callbacks_controller.rb
- config/saml/metadata/uat.xml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1660)
Add reset_session to login callback to try and improve robustness of user experience with portal
> EL-1660 Add reset_session to login callback

- README.md
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1694)
Adding some notes on the puppeteer upgrade to README as we haven't documented this anywhere
> EL-1694: Add puppeteer instructions to README

- app/lib/feature_flags.rb
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
- spec/rails_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1713)
Added new session feature flag, turned on in UAT off in other environments.
> EL-1713 Early Eligibility Banner Feature Flag

- app/services/check_answers/sections/case_details.rb
- spec/flows/under_eighteen_flow_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1731)
- fix bug that has been identified, when doing a controlled U18 certificated check
- will be adding more tests for other scenarios
- is a continuation of EL-1631
> EL-1731: U18 Results screen for certificated checks

- app/controllers/change_answers_controller.rb
- app/lib/steps/helper.rb
- app/models/check.rb
- spec/flows/under_eighteen_flow_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1732)
- add in tests for the behaviour we want to see
> EL-1732: Still show the `how-to-aggregate` screen for U18 flow, after changing answers

- app/views/question_flow/applicant.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1752)
Update passporting hint text
see comments on JIRA ticket for the agreed final design for this ticket.
> EL-1752 update passporting hint content

- .github/workflows/gajira.yml
> EL-1726: Implement Gajira in Github Workflow

- .github/workflows/gajira.yml
- Add in PR body as is into the Jira ticket, then strip out if necessary.
> EL-1726: Gajira part 3 

- app/views/results/_limits_table.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1773)
removed content that is no longer valid
> EL-1773 remove old content from results page

- .github/workflows/gajira.yml
- update Jira ticket layout and content
> EL-1726: Gajira part 5

- .github/workflows/gajira.yml
- update wording in Jira description
- add epic/parent link
> EL-1726: Gajira part 6

- .github/workflows/gajira.yml
- update epic link
- used [postman](https://web.postman.co/) in order to do api call to jira to find out `parent link` filed name
> EL-1726: Gajira part 7

- .github/workflows/gajira.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1728)
- removing adding in parent field, as no longer needed. This would require 'configure field layout in the issue view' via a [JIRA admin ](https://confluence.atlassian.com/adminjiraserver/defining-a-screen-938847288.html)
> EL-1726: Gajira part 8

- config/initializers/rails_admin.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1758)
- exclude `providers` model from rails admin
> EL-1758: Remove Portal user emails from CCQ Admin

- app/lib/controlled_work_mappings/civ_means_7_welsh_new.yml
Updated the field ID
This ID has changed from the previous welsh CM7 form, it looks like it is the only one that changed between versions though.
> BUGFIX: CivMeans7 Welsh (Rent)

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
releases new cw forms to stg and prod
> release new  cw forms

- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
change made so we can create some data with the old EE method on UAT main
we will want to revert this change after some test data has been created
> Switch Feature Flag to create EE test data  in UAT

- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
turn ee banner back on. in UAT
> switch eebanner back on in UAT

- db/migrate/20241101120059_add_early_eligibility_result_in_completed_user_journeys.rb
- db/migrate/20241101120059_populate_early_eligibility_result_in_completed_user_journeys.rb
- db/schema.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1833)
Add a new column to the relevant table.
the data migration will be done at another time in another PR.
> EL-1833 (Part1 ) add new column

- app/models/check.rb
- app/services/check_answers/sections/case_details.rb
- spec/flows/certificated_non_passported_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1803)
- add condition so that 'Asylum & Immigration table' not shown when DA check
> EL-1803: Change Answers Bug (Asylum Immigration)

- package.json
- yarn.lock
> EL-1842 4 dependabot updates

- app/helpers/property_helper.rb
- app/lib/feature_flags.rb
- app/views/question_flow/mortgage_or_loan_payment.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1866)
- update on helper to show links on appropriate screens and be behind feature flag
- update on slim file to add hint text and be behind feature flag
- LC guidance is going to somewhere generic until we know what the links are
> EL-1866: CCQ MTR accelerated content updates: Housing

- config/locales/en.yml
makes non-passporting appear on a single line
> MTR Fix benefits header amended

- package.json
- yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1880)
update 2 x packages
there is a separate ticket for the govuk front end upgrade
> EL-1880: update 2 x packages

- app/views/shared/_cost_of_living.html.slim
- app/views/shared/_cost_of_living_payments.html.slim
> MTR Fix add bullet point styling

- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1922)
- update broken link
- n/a
> EL-1922: Replace broken link to legalaidlearning

- app/forms/other_income_form.rb
- spec/forms/other_income_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1807)
- any number below 1.00 but above 0, will no longer set off validation error.
- n/a
> EL-1807: '...income from other sources?' validation 

- public/maintenance.html
Small content tweak to make sure we are using the correct date. This PR is content ONLY.
> Maintenance page content for EE banner switch on and migration

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1833)
- turn off maintenance mode
- n/a
> EL-1833: Turn off maintenance mode

- .circleci/config.yml
Removing/commenting out approval steps in pipeline
> Remove prod and staging approval steps

- app/views/results/_under_eighteen_next_steps.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1810)
- add additional id to certificated print button
- part 2
> EL-1810: CCQ: Track when results are saved as PDF, Part 2

- README.md
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1610)
- update `Readme.md` 
- update dependencies
- re-order structure grouping similar content together
- make it easier to copy commands
- update content
- n/a
> EL-1610: Update CCQ `readme.md` with correct dependancies

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2012)
Bump puppeteer to 24.0.0 following readme instructions for manuall puppeteer upgrade.
> el-2038: bump puppeteer to 24.0.0

- app/views/layouts/_footer.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2019)
Updated link to point at new smart survey link.
Added ids to be used by google tag manager for measuring the number of users that click on these links.
> el-2019: update survey monkey link

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
> Puppeteer 2420

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2113)
- manual upgrade of puppeteer to 24.2.1
- n/a
> EL-2113: Manual upgrade of puppeteer to 24.2.1

- app/helpers/forms_helper.rb
- app/services/external_link_service.rb
- app/views/question_flow/asylum_support.html.slim
- config/locales/en.yml
- spec/forms/asylum_support_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2063)
- new 'details' & 'summary' component added to `Does your client get Asylum Support?` screen for controlled journey
- there will be a separate ticket to look at GA4 analytics
> el-2063: asylum content change for controlled work

- app/controllers/flow/handler.rb
- app/forms/property_landlord_form.rb
- app/lib/steps/logic.rb
- app/lib/steps/outgoings_section.rb
- app/lib/steps/property_section.rb
- app/views/question_flow/property_landlord.html.slim
- config/allowed_analytics_pages.yml
- config/locales/en.yml
- spec/forms/property_landlord_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1616)
Adds the new joint owned other than landlord question page.
TODO:
Navigate to the currect page after clicking Yes or No on the  joint owned other than landlord question page. (These pages are being created in EL-1579 and EL-1947)
> El 1616 joint owned other than landlord question

- app/controllers/flow/handler.rb
- app/forms/base_housing_costs_form.rb
- app/forms/housing_costs_form.rb
- app/forms/shared_ownership_housing_costs_form.rb
- app/lib/steps/outgoings_section.rb
- app/lib/steps/property_section.rb
- app/services/cfe/regular_transactions_payload_service.rb
- app/services/cfe_param_builders/regular_transactions.rb
- app/views/question_flow/_shared_ownership.html.slim
- app/views/question_flow/housing_costs.html.slim
- app/views/question_flow/property_entry.html.slim
- app/views/question_flow/shared_ownership_housing_costs.html.slim
- app/views/shared/_money_input_no_label.html.slim
- config/allowed_analytics_pages.yml
- config/locales/en.yml
- spec/flows/household_flow_spec.rb
- spec/forms/shared_ownership_housing_costs_form_spec.rb
- spec/models/housing_costs_form_spec.rb
- spec/models/shared_ownership_housing_costs_form_spec.rb
- spec/services/cfe/regular_transactions_payload_service_spec.rb
- spec/support/flow_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1579)
added new template for shared_ownership housing costs
split housing cost form to use a base form
add shared ownership housing costs form
add tests to cover new form
TODO:
currently the shared_ownership_housing_costs page is not shown if an additional property is marked as shared_ownership
I had a look at the figma and it was not clear to me where this new page would be shown, although it would seem to make sense to show it straight after the question is asked. This need clarification and I think would warrant being in its own ticket as this one feels like it has grown legs already.
- Branch is generally up to date with main Github - definitely no …
> EL-1579 shared home costs

- app/views/start/index.html.slim
- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2168)
- If applied, this change will add text to start page based on feature flag
- n/a
> EL-2168: Shared ownership - start page content

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2197)
manual upgrade of puppeteer 
> EL-2197 manual upgrade of puppeteer to 24.4.0

- app/models/dependant_income_model.rb
- config/locales/en.yml
- spec/forms/dependant_income_details_form_spec.rb
- spec/models/dependant_income_model_spec.rb
- spec/models/housing_costs_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2195)
change the way we calculate monthly equivalents in CCQ to mirror what we do in CFE. We only do this for validation so we should use the CFE method. 
> EL-2195 Dependent Income Validation

- spec/forms/dependant_details_form_spec.rb
- spec/views/results_page/housing_outgoings_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2139)
- If applied, this fixes tests that have broken due to 7th April 2025 threshold changes.
- n/a
> EL-2239: Fix CCQ pipeline due to failing threshold tests

- app/lib/feature_flags.rb
- app/models/dependant_income_model.rb
- spec/end_to_end/without_partner_spec.rb
- spec/forms/dependant_income_details_form_spec.rb
- spec/models/dependant_income_model_spec.rb
- spec/views/results_page/client_financial_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2158)
- If applied this removes `thresholds_2025` feature flag
- also updating the tests 
- n/a
> EL-2158: Remove `thresholds_2025` feature flag

- config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1562)
This ended up quite a manual process as running CHECK_UNUSED_KEYS=true bundle exec rspec produces quite a few false positives - it will need some careful uat/regression testing.
> El 1562 remove unused translations

- app/controllers/change_answers_controller.rb
- app/lib/steps/helper.rb
- spec/flows/certificated_passporting_spec.rb
- spec/flows/change_answers_flow_spec.rb
- spec/flows/shared_ownership_flow_spec.rb
- spec/support/flow_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2222)
Adds a test for the existing flow which is working
this is part A of this ticket, this is the test that we must not break while trying to fix check answers loops
> EL-2222 Shared ownership Check Answers flow

- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2142)
- If applied, this turns on CCQ in staging for metabase testing
- n/a
> EL-2142: Turn on `shared_ownership` for CCQ metabase testing

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
> Manual upgrade of puppeteer to 24.6.1

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
> Puppeteer 2472

- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2803)
Enable shared ownership in production
> el-2803: enable shared ownership in production

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
> Puppeteer 2480

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
- If applied, this will update puppeteer to 24.8.2
- n/a
> EL-2332: Update puppeteer to 24.8.2

- app/helpers/forms_helper.rb
- app/lib/feature_flags.rb
- app/views/start/index.html.slim
- helm_deploy/laa-estimate-eligibility/templates/_envs.tpl
- helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml
- helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
- spec/flows/cannot_use_service_flow_spec.rb
- spec/flows/change_answers_flow_spec.rb
- spec/flows/shared_ownership_flow_spec.rb
- spec/forms/additional_property_form_spec.rb
- spec/forms/property_form_spec.rb
- spec/forms/property_landlord_form_spec.rb
- spec/forms/shared_ownership_housing_costs_form_spec.rb
- spec/rails_helper.rb
- spec/services/cfe/assets_payload_service_spec.rb
- spec/views/results_page/housing_outgoings_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2308)
Remove shared ownership flag
> el-2308: remove shared ownership flag

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2467)
Update puppeteer
> Puppeteer 24111

- .circleci/config.yml
- .github/workflows/browser_tools_docker_image.yml
- Dockerfile_browser_tools.dockerfile
- package.json
- yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-)
- If applied, this updates to "puppeteer": "24.22.0"
- this updates this PR -> https://github.com/ministryofjustice/laa-check-client-qualifies/pull/1982
> EL-2664: Updates to puppeteer, 24.22.0
