ministryofjustice/laa-check-client-qualifies

config/environments/development.rb, config/environments/production.rb
The first PR for EL-282 didn't remove the database references from the environment files. This removes them so that tasks like rake assets:precompile work without crashing
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-282)
=> EL-282 remove database (from environment files)

.circleci/config.yml, README.md, config/application.rb
https://dsdmoj.atlassian.net/browse/EL-259
According to this post https://stackoverflow.com/questions/71262775/how-do-i-ensure-assets-are-present-with-rail-7-cssbundling-rails-jsbundling-ra propshaft is a lot less supportive than previous asset pipelines. However it turns out that disabling the rails 'tests' railtie caused certain hooks to be removed - specifically a silent 'test:prepare' rake task, which when enabled makes the assets up-to-date for a 'rake spec' run
=> Propshaft assets in test mode

.circleci/config.yml
Currently we are deploying all builds to ECR and staging - this is slow and is resulting in resource clashes for the staging environment
=> Restrict ECR and deploy tasks to main branch

config/environments/production.rb
One of the security checks added the force_ssl flag to our production config, but this is incorrect as we deploy behind an SSL-enabled reverse proxy
=> Remove force-ssl config as we are behind an SSL reverse proxy

spec/features/applicant_page_spec.rb
The original source of the defect on number formatting was the lack of a test.
This adds the test to the PR which fixes the defect
=> Add test for results page defect

app/views/build_estimates/results.html.erb, spec/features/applicant_page_spec.rb
I didn't spot this when reviewing #33, but there's a very small config bug in a view file, where we're using [number_with_precision](https://apidock.com/rails/ActionView/Helpers/NumberHelper/number_with_precision) to format a decimal value. This was resulting in, e.g., `1234.56`, which should be rendered as `£1,234.56`, instead being rendered as `£1234,56`.
Checklist
You should have looked at the diff against main and ensured that …
=> Bugfix: Formatting of monetary values on final results page

app/controllers/flow/summary_handler.rb
Remove code duplication around applicant handling
=> Dry up applicant data handling

bin/uat_deployment
kubernetes has an issue if names are too long. The script needs to cut more of the branch name before using that as the release/ingress name. This changes the script to use only the first 20 characters of the branch name.
Checklist
=> Bugfix: update deployment script to fix k8s naming length issue

.circleci/config.yml, bin/delete_uat_deployment
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-380)
I decided to implement it as a circleci job instead of github action mainly because it requires the ENV_VARS such as K8S_NAMESPACE, K8S_CLUSTER_CERT etc to be set up on Github. We already have these ENV_VARS on circle for managing deployments so it seemed like a bit of duplication before even starting.
Add a new job to circleci to call a script to check if a deployment needs to be deleted
Add a script to check releases and delete the ones associated with a merged PR
Checklist
There should be no unnecessary whitespace changes. These make diffs harder to read …
=> EL-380 Add circleci job to delete helm deployments

.circleci/config.yml, bin/delete_ecr_images
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-332)
Added a nightly job to circleci to clean up ECR images older than 10 days. This is pretty much lifted from the Legal Framework PR that does the same thing for that repo. As such I have not implemented a kubernetes cronjob to do this task (as mentioned in the ticket) but used circleci nightly function.
*NOTE*  
The nightly function used by circleci is due to be deprecated by the end of 2022, as such this method will need to be changed to a cronjob/scheduled pipeline/github action at some point, but this will work for now and avoid any cloud platform alerts
https://support.circleci.com/hc/en-us/articles/115015983008-Scheduling-a-Nightly-Build
Checklist
Tests and rubocop should be …
=> EL-332 Add delete script and job to circleci

bin/delete_uat_deployment
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-380)
Use of the --purge flag to delete helm instances is no longer necessary as this is now part of the default helm delete command
Checklist
=> EL-380 bugfix: Remove purge flag as it is now the default for delete commands

bin/delete_uat_deployment
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-380)
Third time lucky:
The helm delete command was missing an extra hyphen before the namespace flag
Checklist
=> EL-380 (further fix)add required hyphen on namespace flag

app/controllers/flow/monthly_income_handler.rb, spec/features/monthly_income_page_spec.rb
Previously you could check 'student loan', enter a value, then uncheck it, and the value you had entered would still be sent. This fixes that.
=> Bugfix: Stop us sending student loan values if loan box is unchecked

app/forms/assets_form.rb, app/forms/employment_form.rb, app/forms/monthly_income_form.rb, app/forms/outgoings_form.rb, app/forms/property_entry_form.rb, app/forms/vehicle_finance_form.rb, app/forms/vehicle_value_form.rb, app/helpers/application_helper.rb, app/views/shared/_money_input.html.slim, app/views/shared/_money_input_with_hint.html.slim, config/initializers/attribute_types.rb, spec/features/assets_page_spec.rb, spec/features/employment_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-377)
- We allow users to enter "," in their financial amounts, and discard them when we cast them into a model
- We also discard anything beyond 2 decimal places
- When rendering a form input containing a monetary value a user has previously inputted:
- If the user had previously entered no decimal places, or the value is already rounded to the nearest pound, we don't display pence
- Otherwise we display pence to 2 decimal places
- In all cases we show "," thousand separators to improve readability 
- (Also fix a minor bug where we were re-sending the student loan value to CFE even after the student loan checkbox had been unchecked)
=> EL-377: Use a forgiving, nicely formatted money input

app/forms/employment_form.rb, config/locales/en.yml, spec/features/employment_page_spec.rb
At the moment, if the user enters a negative net income this is sent to CFE which validates it and returns n (unfriendly) 422 error. This moves the validation onto EFE so the user can be informed.
https://dsdmoj.atlassian.net/browse/EL-389
=> EL-389 Warn if user enters negative (net) income

app/views/estimate_flow/case_details.html.slim
We have `govuk-grid-row` in our layout, so putting another one at the root of the view file leads to too much padding in places.
=> BUG: Case details layout issue means sidebar is fractionally misaligned

app/views/shared/_sidebar_with_date.html.slim
Somehow the sidebar html got wrongly indented so sidebar contents aren't being rendered inside the correct layout div.
=> Fix sidebar slimdentation

app/lib/income_section.rb, app/presenters/check_answers_fields.yml, app/views/estimate_flow/_two_column_check_answer.html.slim, app/views/estimate_flow/check_answers.html.slim, config/locales/en.yml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-416)
Add a new two-column summary format and use it for the values/frequencies entered in the new 'Outgoings' screen.
Checklist
=> EL-416: Check outgoings answers

app/views/estimate_flow/employment.html.slim, spec/features/employment_page_spec.rb, spec/features/result_page_spec.rb, spec/system/employment_page_spec.rb
In research, providers have been confused about entering the amount of salary before the frequency, so move the frequency first. Convert to a set of radio buttons for accessibility.
https://dsdmoj.atlassian.net/browse/EL-437
=> EL-437 Prompt for employment income frequency using radio buttons

.github/actions/delete-uat-release/action.yml, .github/workflows/delete_uat_release.yml
Add a github action to delete UAT releases when a PR is merged with main or closed.
Add secrets to the repo via the cloud platform namespace - https://github.com/ministryofjustice/cloud-platform-environments/pull/9101
The circleci job does not delete UAT releases when a PR is opened and subsequently closed without merging. This job will be removed in a subsequent PR
Checklist
You should have looked at the diff against main and …
=> add github action to delete UAT release on merge or close of PR

app/models/calculation_result.rb, app/views/estimates/_client_capital_table.html.slim, config/locales/en.yml, spec/features/result_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-433)
The numbers in the capital table now "add up" - we show the assessed value of every sort of asset, then the total assessed value, then the disregards, then the assessed disposable capital which is the  total assessed value minus the disregards.
Checklist …
=> EL-433: Show SMOD disregards in capital summary table

app/services/check_answers/section_lister_service.rb, spec/features/check_answers_page_spec.rb, spec/support/form_helpers.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-444)
Fix bug that meant benefits section was shown on the check answers screen when it shouldn't be.
=> EL-444: Fix bug in check answers benefits section logic

app/controllers/benefits_controller.rb, app/controllers/check_benefits_answers_controller.rb, app/helpers/application_helper.rb, app/views/benefits/edit.html.slim, app/views/benefits/new.html.slim, spec/features/check_answers_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-445)
In the normal run of things, when you delete the only benefit you get taken to the 'add a benefit' screen. This was a deliberately requested feature. If you don't _want_ to add a benefit your only option is to click 'Back'. Because this was previously a JS-powered back button, it would take you back to the benefits list screen without triggering a page refresh... which would mean you would still see the benefit you'd just remove listed.
So this PR removes the JS-powered back and replaces it with a proper back button.
Also, if from the check answers screen you choose to 'Remove' the benefit rather than 'Change' it, that suggests you don't want to replace the benefit with a different one. So it would not be appropriate to …
=> EL-445: Fix 'delete the only benefit' flow

app/lib/applicant_case_details_section.rb, spec/features/applicant_page_spec.rb, spec/features/change_employment_type_spec.rb, spec/support/form_helpers.rb, spec/system/assets_page_spec.rb, spec/system/vehicle_page_spec.rb
When a client is receiving passported benefits, their dependants do not contribute to the calculation of eligibility, so don't ask the question in that case
https://dsdmoj.atlassian.net/browse/EL-446
=> EL-446 Don't display dependants questions when user is passported

spec/features/employment_page_spec.rb
whilst refactoring, I noticed that the employment CFE intertaction could be broken without tests failing. This adds some more checks so that can't happen any more.
=> Add extra employment tests

app/services/check_answers/applicant_section.rb, spec/features/applicant_page_spec.rb
The SMOD merge accidentally removed some work done after it to show partner employment and age summaries on the check answers screen. This re-adds that work (doing it differently this time to use the new `Section` object) and adds a test to make sure it can't go missing again.
=> Re-add conditional logic around partner field display

app/models/calculation_result.rb, spec/features/result_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-450)
When CFE thinks a client has no relevant disposable capital it sometimes expresses it as negative disposable capital (specifically if the client has < £100k of disposable capital and is over 60, so has a £100k pensioner disregard applied). This PR ensures that when the assessed capital returned by CFE is negative, we show a zero to the user instead of a negative number.
Checklist
The PR description should say what you changed and why, with a link to …
=> EL-450: Compensate for CFE's over-eager pensioner disregard

app/forms/applicant_form.rb, spec/features/applicant_page_spec.rb
https://dsdmoj.atlassian.net/browse/EL-525
Rework applicant spec, resulting in improved tests and tweak to applicant form validation so that errors appear in a logical order
=> EL-525 part one - rework applicant spec (and re-ordered form validation)

app/forms/base_assets_form.rb, app/forms/base_property_entry_form.rb, app/forms/client_property_entry_form.rb, app/forms/dependant_details_form.rb, app/forms/employment_form.rb, app/forms/other_income_form.rb, app/forms/outgoings_form.rb, app/helpers/application_helper.rb, app/services/check_answers/other_section.rb, app/views/estimate_flow/forms/_assets.html.slim, app/views/estimate_flow/forms/_dependant_details.html.slim, app/views/estimate_flow/forms/_property_entry.html.slim, config/initializers/attribute_types.rb, config/locales/en.yml, spec/features/assets_page_spec.rb, spec/features/dependant_details_page_spec.rb, spec/features/employment_page_spec.rb, spec/features/partner_assets_page_spec.rb, spec/features/result_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-565)
- Allow users to enter non-number characters into integer input fields
- If the user enters something non-numeric into an integer or money field, retain the string value and use a `numericality` validation to flag its issues
- Display the original string value back to the user alongside the validation message if user-entered value is non-numeric
=> EL-565: smarter number fields

.circleci/config.yml
https://dsdmoj.atlassian.net/browse/EL-558
Add approval step before production deploy so that we can deploy to production out of hours in case it causes disruption
=> EL-558 Add approval step before production deploy

helm_deploy/laa-estimate-eligibility/templates/deployment.yaml
See: https://github.com/puma/puma/blob/master/docs/kubernetes.md#running-puma-in-kubernetes
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-569)
Describe what you did and why.
Added the sleep in preStop, to delay the point when Puma ignores incoming requests, so that it is definitely after the point when nginx stops sending it requests.
Checklist
You should have looked at the diff against main and ensured that …
=> EL-569 Workaround for Puma/k8s dropped request problem

app/views/shared/_sidebar_with_date.html.slim
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-575)
Make sure that the 'h2' element only contains the heading, not the content beneath it.
=> EL-575: Separate out headings from content in sidebar

app/forms/partner_details_form.rb, app/views/estimate_flow/partner_details.html.slim, spec/features/applicant_page_spec.rb, spec/features/property_page_spec.rb
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-580)
Made the partner employment question conditional on the passporting question, update the validation to be flexible for the page.
Update tests
Checklist
[EL-580]: …
=> EL-580 hide partner employment question when client is passported

.circleci/config.yml
The sequential ECR push step in circle slows down testing of our deployment issues - this makes it parallel so that we can deploy quicker. It also brings us in line with the Circle:CI flow used by apply
=> Parallelise ECR push step to save 1min 30sec during deployment testing

app/lib/check_answers_fields.yml, app/services/check_answers/applicant_section.rb, config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-601)
We weren't showing summaries for the 'passporting' or 'proceeding type' attributes on the 'check answers' screen.
=> EL-601: Missing fields on check answers

infrastructure/laa-estimate-financial-eligibility-for-legal-aid-uat/ingress-dashboard.yaml
[Link to the Jira ticket](https://dsdmoj.atlassian.net/browse/EL-537
I took the currently live "Check if your client qualifies for legal aid - UAT - Ingress" dashboard in Grafana and duplicated the HTTP status requests chart. I renamed the duplicate to 'Request HTTP Errors' and filtered the data to include only 4XX and 5XX status codes. Then I exported the JSON and overwrote the JSON in ingress-dashboard.yml. Finally I checked the diff with what's on `main` and removed any extraneous changes. It looks like what's in main didn't include the `Pod counts by status` chart, so I've included the JSON for that as well.
=> EL-537: Add chart of error rate

app/views/estimates/_income_row.html.slim, app/views/estimates/_income_table.html.slim, app/views/estimates/_outgoings_row.html.slim, app/views/estimates/_outgoings_table.html.slim, config/locales/en.yml, spec/features/result_page_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-621)
Update the income and outgoings rows as per the ticket. Note this PR adds hint text as a new HTML element within a `td` rather than a new row. Note also to complete this ticket there is also a CFE PR: https://github.com/ministryofjustice/check-financial-eligibility-partner/pull/59
=> EL-621: Income and outgoings tables

app/views/estimates/_limits_table.html.slim, app/views/estimates/print.html.slim, app/views/estimates/show.html.slim, config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-620)
Added a new partial to display content around gross, disposable and capital limits on the results page
=> EL-620 add new accordion section

app/models/calculation_result.rb
decision it is always present in the API response, so it doesn't need to be defaulted.
It is worth noting that the style a = something || 0 doesn't get caught by the coverage tools - the || 0 is not considered a branch.
=> Decision doesn't need to be defaulted 

app/views/estimate_flow/applicant.html.slim, app/views/estimate_flow/dependant_details.html.slim, app/views/estimate_flow/partner_dependant_details.html.slim, config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-669)
[Original PR](https://github.com/ministryofjustice/laa-estimate-financial-eligibility-for-legal-aid/pull/395). I merged this into the wrong place and then force pushed in the wrong place and lost this change
=> Deja vu? New guidance links on applicant and dependant pages

app/controllers/benefits_controller.rb, app/views/benefits/edit.html.slim, app/views/benefits/new.html.slim, app/views/estimate_flow/benefits.html.slim, app/views/estimate_flow/partner_benefits.html.slim, app/views/partner_benefits/edit.html.slim, app/views/partner_benefits/new.html.slim, app/views/shared/_disregarded_benefits_sidebar.html.slim, config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-645)
Make the disregarded benefits partial more flexible for levels of help 
=> EL-645 benefits guidance for controlled work

app/controllers/application_controller.rb, app/controllers/benefits_controller.rb, app/controllers/build_estimates_controller.rb, app/controllers/check_answers_controller.rb, app/controllers/check_benefits_answers_controller.rb, app/controllers/check_partner_benefits_answers_controller.rb, app/controllers/estimate_flow_controller.rb, app/controllers/estimates_controller.rb, app/controllers/partner_benefits_controller.rb, app/helpers/application_helper.rb, app/services/analytics_service.rb, app/services/base_cfe_service.rb, app/services/cfe_service.rb, app/services/submit_applicant_service.rb, app/services/submit_assets_service.rb, app/services/submit_benefits_service.rb, app/services/submit_dependants_service.rb, app/services/submit_employment_income_service.rb, app/services/submit_irregular_income_service.rb, app/services/submit_partner_service.rb, app/services/submit_proceedings_service.rb, app/services/submit_regular_transactions_service.rb, app/services/submit_vehicle_service.rb, app/views/estimates/_check_answer.html.slim, app/views/estimates/_check_answers_table.html.slim, app/views/estimates/_money_and_frequency_check_answer.slim, app/views/estimates/check_answers.html.slim, app/views/estimates/show.html.slim, config/routes.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-709)
Separate estimate_id into concepts of assessment_code and assessment_id. This way we have one thing that appears in URLs (and therefore also appears in logs alongside user IP), and something else that is the key to all the user entered financial values stored in Redis. 
While I'm here, rename all other instances of `estimate_id` that aren't baked in by the framework, as neither CCQ nor CFE officially deals with estimates, they deal with checks and assessments.
- PR description says …
=> EL-709: De-identify user in logs

app/services/submit_proceedings_service.rb, spec/services/submit_proceedings_service_spec.rb
Since 10 feb, main has had a bug where domestic abuse proceeding types are ignored if the controlled feature flag is not enabled.
=> Fix bug when controlled flag not enabled

Dockerfile, docker/run, docker/wait_for_pg
The first issue was that we had multiple `CMD` statements in the Dockerfile, so the `migrate` one was being ignored. We also saw that Apply and CFE build in a conditional wait in case the UAT postgres pods aren't ready at first to accept migration commands. While we've not hit that issue yet, and at the risk of cargo culting a mystery shell script, it seemed sensible to have this precautionary measure in place.
=> EL-754: CCQ deployments not running db migrations

app/views/estimate_flow/forms/_property_entry.html.slim, app/views/estimate_flow/property_entry.html.slim, config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-776)
We need to remove some hint text from the 'About their home' section for controlled and certificated flows. We also need to remove one of the bullets from the 'Level of help' page.
This PR removes the hint text and the bullet.
=> [EL 776] Remove hint text from About their home and bullet from Level of help

app/models/calculation_result.rb, app/views/estimates/_capital_table.html.slim, app/views/estimates/_disposable_capital_table.html.slim, spec/features/result_page_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-758)
Only show capital subtotal figures when they're not duplicated elsewhere
Correctly display client capital subtotal
=> EL-758: Fix disposable capital

app/forms/client_property_entry_form.rb, app/lib/check_answers_fields.yml, app/services/check_answers/property_section.rb, app/services/submit_assets_service.rb, app/views/estimate_flow/forms/_property_entry.html.slim, app/views/estimate_flow/property_entry.html.slim, config/locales/en.yml, spec/features/property_page_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-770)
Change wording on property screens, and remove joint ownership percentage questions
=> El-770: Alt partner property screens

app/services/health_check_service.rb, spec/requests/statuses_controller_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-783)
Add a check to see if the database is healthy. This is important n UAT environments because if the DB pod has been cycled (and so hasn't had migrations applied), this will cause the web server pod to cycle, in turn ensuring migrations to run on the DB pod.
=> EL-783: Add database health check

app/models/calculation_result.rb, config/locales/en.yml, spec/factories/api_results.rb, spec/views/results_page/client_financial_content_spec.rb, spec/views/results_page/partner_financial_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-803)
In capital assets (additional home, vehicle, jewellery, savings etc) we were using the `subject_matter_of_dispute_disregard` value. This value includes the disregard for disputed main property and therefore did not look accurate on the results page. We are now using a new field, `disputed_non_property_disregard` which is a total of disregarded assets not including the main property.
- Diff has been checked …
=> [EL-803] Add disputed_non_property_disregard into capitals

app/controllers/build_estimates_controller.rb, app/controllers/check_answers_controller.rb, app/controllers/estimate_flow_controller.rb, app/services/choice_analytics_service.rb, app/services/metrics_service.rb, spec/forms/level_of_help_form_spec.rb, spec/services/choice_analytics_service_spec.rb, spec/services/metrics_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-793)
Use the contents of a form to generate an analytics event and use that event in our metrics. And make it very clear why we should only do that very rarely.
=> EL-793: Use a specific analytics event to track level of help

package.json, spec/system/accessibility_spec.rb, yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-795)
- Use frontend 4.5
- Ignore an accessibility issue on the results screen that's a known issue with that version (and while it's always been there, is now picked up by the tests)
- Fix the print screen tests so that they test the correct page (meaning those tests no longer fail due to an issue on the results page)
- Commit messages say why the …
=> EL-795: Fix accessibility issues associated with govuk-frontend 4.5

config/locales/en.yml, spec/factories/session.rb, spec/services/cfe/submit_assets_service_spec.rb, spec/services/cfe/submit_vehicle_service_spec.rb, spec/support/view_helpers.rb, spec/views/check_answers_page/client_content/assets_spec.rb, spec/views/check_answers_page/client_content/dependants_spec.rb, spec/views/check_answers_page/client_content/employment_spec.rb, spec/views/check_answers_page/client_content/housing_benefit_spec.rb, spec/views/check_answers_page/client_content/other_benefits_spec.rb, spec/views/check_answers_page/client_content/other_income_spec.rb, spec/views/check_answers_page/client_content/outgoings_spec.rb, spec/views/check_answers_page/client_content/property_spec.rb, spec/views/check_answers_page/client_content/special_client_types/asylum_and_immigration_spec.rb, spec/views/check_answers_page/client_content/special_client_types/passported_client_spec.rb, spec/views/check_answers_page/level_of_help_sidebar_content_spec.rb, spec/views/check_answers_page/partner_content/assets_spec.rb, spec/views/check_answers_page/partner_content/dependants_spec.rb, spec/views/check_answers_page/partner_content/employment_spec.rb, spec/views/check_answers_page/partner_content/housing_benefit_spec.rb, spec/views/check_answers_page/partner_content/other_benefits_spec.rb, spec/views/check_answers_page/partner_content/other_income_spec.rb, spec/views/check_answers_page/partner_content/outgoings_spec.rb, spec/views/check_answers_page/partner_content/property_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-782)
We didn't have any tests checking that the content of a session was rendering correctly on the Check answers page. This ticket adds view specs.
I have also added a factory called 'minimal_complete_session' - I'm not sure if this is useful, but I wanted to create the minimum viable session that would have progressed through the main flow, to the check answers page. My thinking was it is then easier to tack on other attributes or traits to this and be confident that there isn't anything else in the factory that could skew you test.
- No unnecessary whitespace changes. These make …
=> [EL-782] Add tests for Check answers page

app/services/metrics_service.rb, helm_deploy/laa-estimate-eligibility/templates/_envs.tpl, helm_deploy/laa-estimate-eligibility/values/production.yaml, helm_deploy/laa-estimate-eligibility/values/staging.yaml, helm_deploy/laa-estimate-eligibility/values/uat.yaml, spec/services/metrics_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-791)
Create a new dataset that contains the most common pages on which incomplete checks are abandoned, for both the current month and all time, divided by controlled vs certificated
=> EL-791: Add a query to surface the last page reached for incomplete checks

app/helpers/applicant_helper.rb, spec/forms/applicant_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-811)
Only show domestic abuse guidance where it is relevant.
For certificated work, domestic abuse cases have different rules applied, but for controlled they don't. So we only show an 'is this domestic abuse' case for certificated work. Furthermore, when we release asylum and immigration we'll stop asking the domestic abuse question on the applicant screen and will instead ask it on the matter type screen.
So we only want to show the domestic abuse guidance if it's _not_ controlled work and the A&I feature flag is _not_ enabled.
- No unnecessary whitespace changes. These make diffs …
=> EL-811: Hide domestic abuse guidance where not relevant

app/models/calculation_result.rb, app/views/estimates/_capital_table.html.slim, app/views/estimates/_income_table.html.slim, app/views/estimates/_ineligible_explanation.html.slim, app/views/estimates/_outgoings_table.html.slim, config/locales/en.yml, spec/views/results_page/eligibility_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-818)
Add missing ineligibility explanation at bottom of tables on results page
The CFE response shows whether each section (gross income, disposable income, capital) is ineligible by associating an "ineligible" result string with one or more of the proceeding types that are attached to that section. But in CCQ there is only ever one proceeding type, because we only ever feed CFE one proceeding type for a check.
- …
=> EL-818: Extra ineligibility line on results page

helm_deploy/laa-estimate-eligibility/values/staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-834)
Stop sending staging analytics data to geckoboard. This is because we have never yet used staging data on Geckoboard, and don't have any boards set up for it. Furthermore, we're about to start switching off the staging database at night, so the nightly job that's supposed to push data to Geckoboard will fail if it tries to run. So we might as well stop it trying.
- Diff has been checked for unexpected …
=> EL-834: Disable staging geckoboard

app/lib/check_answers_fields.yml, app/views/estimates/_check_answers_table.html.slim, config/locales/en.yml, spec/views/check_answers_page/client_content/special_client_types/asylum_and_immigration_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-833)
If a check answers select field has an `alt_attribute` key, use that to construct the I18n key for the value text. That way we can use both the level of help and the proceeding type to determine what text to show for the 'What type of matter is this?' check answers field.
=> EL-833: Check your answers matter type text

app/models/calculation_result.rb, spec/factories/api_results.rb, spec/views/results_page/pensioner_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-831)
If pensioner disregard has been applied to partner capital but not client (i.e. if client has no capital to apply it to), still show the pensioner disregard standalone table.
I'm basing this of EL-828 as that had some refactors of the api result factory that made writing this test much easier.
=> EL-831: Show pensioner table if only partner has pensioner disregard applied

app/models/calculation_result.rb, spec/views/results_page/pensioner_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-828)
- We weren't including the pensioner disregard values applied to partner capital in the pensioner disregard table
- Also we were using `total_capital` rather than `total_capital_with_smod` in the first line, which was sometimes showing incorrect values (because SMOD has already been deducted by the time this table is displayed)
I have asked the CFE team if they can do the maths for us to save us doing `+`, and they will do this as a low-priority thing. In the meantime we will do the `+`.
- No unnecessary whitespace changes. These make diffs harder to read and conflicts more …
=> EL-828: Use correct values for pensioner disregard table when there is a partner

app/controllers/application_controller.rb, app/controllers/cookies_controller.rb, app/controllers/estimate_flow_controller.rb, app/helpers/application_helper.rb, app/services/analytics_service.rb, app/services/choice_analytics_service.rb, app/views/layouts/_analytics_body.html.slim, app/views/layouts/_analytics_head.html.slim, app/views/layouts/_footer.html.slim, config/locales/en.layouts.yml, config/routes.rb, spec/features/no_analytics_mode_spec.rb, spec/services/analytics_service_spec.rb, spec/services/choice_analytics_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-835)
Create a new "no-analytics mode" a state, marked by a cookie, in which no analytics data will be stored and no Google Analytics will be generated. Visiting a new URL will cause this mode to be entered, and a badge to be shown in the footer. The user will stay in this mode for the duration of their browser session. 
- Commit messages say why the …
=> EL-835: no-analytics mode

app/services/cfe_param_builders/vehicles.rb
We have an issue live in production where client vehicle subject_matter_of_dispute is being sent to CFE as nil when the client has a vehicle and the case is upper tribunal (because we don't ask the SMOD question in that scenario so the relevant value isn't set). At some point CFE made that field a mandatory boolean. This ensures that if we have a `nil` value we tell CFE it is `false` as a workaround.
=> Ensure vehicle SMOD is never nil

app/views/shared/_money_input.html.slim, app/views/shared/_money_input_with_hint.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-849)
Fix issue where on mobile you aren't allowed to enter a "." on money fields
- The "inputmode" attribute hints to mobiles what sort of keypad to display
- The "pattern" is used for client-side validation, but since we don't _do_ that it's redundant so I've removed it.
=> EL-849: Hint to mobile browsers that soft keypad should include decimal points

app/lib/check_answers_fields.yml, spec/views/check_answers_page/client_content/property_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-879)
Only show "check answers" fields for property questions that the user gets asked. This fixes a bug introduced in #499 
=> EL-879: Check answers joint ownership bugfix

app/views/estimate_flow/household_flow/_partner_details.html.slim, app/views/estimate_flow/non_household_flow/_partner_details.html.slim, app/views/estimate_flow/partner_details.html.slim, config/locales/en.yml, spec/forms/partner_details_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-865)
Added an alternative version of the partner details form
Added a missing partner details form spec
I'm trying to avoid doing the household flow with a bunch of fiddly "if" statements that we'll have to unpick when we remove the household flow feature flag. So instead I'm using two different view partials. In this case they're very similar, so not super DRY, but I think that, as this is only temporary duplication due to feature flag-based rollout, that's ok. 
- PR description says …
=> EL-865: New version of partner details for household flow

app/forms/base_assets_form.rb, app/lib/feature_flags.rb, app/views/estimate_flow/forms/_dependant_details.html.slim, app/views/estimate_flow/household_flow/_partner_assets.html.slim, app/views/estimate_flow/household_flow/forms/_assets.html.slim, app/views/estimate_flow/non_household_flow/_partner_assets.html.slim, app/views/estimate_flow/non_household_flow/forms/_assets.html.slim, app/views/estimate_flow/partner_assets.html.slim, config/locales/en.yml, spec/forms/dependant_details_form_spec.rb, spec/forms/partner_assets_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-864)
Partner assets screen in household flow has different copy and fields.
=> EL-864: Household flow partner assets screen

app/views/estimate_flow/forms/_assets.html.slim, app/views/estimate_flow/forms/_property_entry.html.slim, app/views/shared/_percentage_input.html.slim, app/views/shared/_percentage_input_with_hint.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-888)
When using CCQ on a ‘mobile device’ screen, and you are asked to input percentage share of an housing asset. The user is now shown a numerical screen keyboard (without decimal) not a qwerty screen keyboard. 
Please check that this works on both client and partner flows. 
=> EL-888: Keyboard input for percentages on mobile screen

app/controllers/estimates_controller.rb, app/lib/steps/helper.rb, app/views/estimates/check_answers.html.slim, app/views/estimates/show.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-893)
The 'back' button on the results page now always leads back to the check answers page.
The one of the check answers page now always leads back to the last step in the flow.
=> EL-893: Fix js back buttons

app/lib/steps/partner_section.rb, app/views/estimate_flow/dependant_details.html.slim, app/views/estimate_flow/household_flow/_dependant_details.html.slim, app/views/estimate_flow/non_household_flow/_dependant_details.html.slim, app/views/estimate_flow/non_household_flow/forms/_dependant_details.html.slim, app/views/estimate_flow/partner_dependant_details.html.slim, config/locales/en.yml, spec/features/number_fields_spec.rb, spec/flows/household_flow_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-853)
Combined dependants screen in household flow
Note new pattern used for verbose hint content in a a `govuk_radio_buttons_fieldset`, using `content_for` to break it out into a separate place rather than having to write it as Ruby code.
=> EL-853: New combined dependants screen

app/controllers/controlled_work_document_selections_controller.rb, app/mailers/exception_alert_mailer.rb, app/models/completed_user_journey.rb, app/services/journey_log_update_service.rb, app/services/metrics/from_completed_journeys_service.rb, db/migrate/20230516083704_add_form_downloaded_to_completed_user_journey.rb, db/schema.rb, spec/forms/controlled_work_document_selection_spec.rb, spec/services/journey_log_update_service_spec.rb, spec/services/metrics/from_completed_journeys_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-892)
Add CW download analytics data, both analytics events and user journey attributes.
I added a guard clause in `ExceptionAlertMailer` because often that class errors in tests when it's triggered by an exception being raised somewhere else, leading to an error message about the internals of ExceptionAlertMailer that says nothing about what went wrong re the actual functionality being tested.
- Diff has been …
=> EL-892: Add metrics around CW forms

app/views/accessibilities/_list.html.slim, app/views/accessibilities/show.html.slim, app/views/cookies/show.html.slim, app/views/estimate_flow/matter_type.html.slim, app/views/estimates/_controlled_work_next_steps.html.slim, app/views/estimates/_limits_table.html.slim, app/views/estimates/print.html.slim, app/views/estimates/show.html.slim, app/views/layouts/_cookie_banner.html.slim, app/views/layouts/application.html.slim, app/views/layouts/print_application.html.slim, app/views/shared/_disregarded_benefits_details.html.slim, config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-904)
`== t(` is bad, because the output of `t` can't always be trusted if it includes interpolated values. Using `t`'s built-in HTML-safe-marking system is better, so we now do that (and, in general, don't use `==` to render _any_ text in views any more.
=> EL-904: Use HTML-safe translations

README.md, app/helpers/assets_helper.rb, app/views/estimate_flow/household_flow/_assets.html.slim, app/views/estimate_flow/non_household_flow/_assets.html.slim, app/views/estimates/_capital_table.html.slim, app/views/estimates/_limits_table.html.slim, app/views/privacies/show.html.slim, app/views/shared/_disregarded_benefits_details.html.slim, config/locales/en.yml, spec/rails_helper.rb, spec/unused_i18n_key_checker.rb
Having poked around at our `en.yml` file for #675 I noticed that there are a few obsolete keys in there. ~I'll raise a ticket to clear them out, but in the meantime~ I've built a little utility to help us detect obsolete keys to make that task easier. Here's a sample of its output:
Update: I have also now cleared out the obsolete keys, and fixed a couple of small bugs where we were wrongly _not_ using a key that we should have been.
=> Utility to detect stale i18n keys

app/views/estimate_flow/household_flow/_property.html.slim, config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-903)
add new details component to the household property page when spag flag is enabled
=> EL-903 add details component to property page

app/lib/steps/applicant_details_section.rb, app/lib/steps/capital_section.rb, app/lib/steps/helper.rb, app/lib/steps/income_section.rb, app/lib/steps/outgoings_section.rb, app/lib/steps/partner_capital_section.rb, app/lib/steps/partner_income_section.rb, app/lib/steps/partner_section.rb, app/views/estimate_flow/mortgage_or_loan_payment.html.slim, spec/flows/household_flow_spec.rb, spec/support/flow_helpers.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-870)
Updated the flow to match the miro board
https://miro.com/app/board/uXjVPBBAi10=/?moveToWidget=3458764552902974344&cot=14
The steps/sections that we use could do with a refactor as the new household flow groups things in a different way. I propose to create a ticket for refactoring the sections when we remove the household_flow feature flag.
- …
=> EL-870 Finalise Household flow

app/helpers/assets_helper.rb, app/views/estimate_flow/household_flow/_partner_assets.html.slim, app/views/estimate_flow/household_flow/forms/_assets.html.slim, config/locales/en.yml, spec/forms/assets_form_spec.rb, spec/forms/partner_assets_form_spec.rb
[Jira ticket 1](https://dsdmoj.atlassian.net/browse/EL-901)
[Jira ticket 2](https://dsdmoj.atlassian.net/browse/EL-902)
New help text for special applicant groups on household flow assets pages
=> EL-901 & EL-902: Special applicants assets

helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-948)
Enabling all UAT feature flags, which were turned off with for UAT'ing EL-938.
=> EL-948: Enabling UAT feature flags

app/lib/controlled_work_mappings/civ_means_7.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-951)
Cheeky typo preventing the population of partner savings on CIVMEANS7 
Also removed a left over note in the code as seems it is now redundant. CIV MEANS 7 has sections for smod and non-smod so I think the use of `non_smod_client_savings` is correct.
=> [EL-951] Fix typo on CIVMEANS7

spec/flows/controlled_work_documents_spec.rb, spec/services/cfe/partner_payload_service_spec.rb
No ticket for this, it was easier to just remove the flags than write a jira ticket.
Removed flags that are no longer in use and the specs dont need them
=> Remove old flags from specs

app/views/estimate_flow/forms/_other_income.html.slim, app/views/estimate_flow/forms/_outgoings.html.slim, app/views/estimate_flow/housing_costs.html.slim, app/views/shared/_money_input.html.slim, config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-906)
Add aria-labels to some input fields to allow for proper screen reader announcements for what should happen with the input field
=> EL-906 Add aria labels

app/lib/steps/property_section.rb, spec/flows/household_flow_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-962)
Prevent the mortgage payments screen for appearing for passported clients
If the client is passported, we don't care about mortgage costs as they only impact disposable income, which is ignored.
=> EL-962: mortgage payments screen showing for passported clients

app/forms/applicant_form.rb, spec/flows/check_answers_flow_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-982)
We introduced a bug when adding the new employment status form. Originally we set the `employment_status` attribute from the applicant form. This has now changed with the new implementation, but we were still setting `employment_status` from the applicant form. It was being set to nil and then redirecting to the employment status form as nil is invalid.
Straight forward - only thing was to check if I could write a better test for this. I've gone with a test of the flow in the `check_answers_flow_spec.rb`
- No unnecessary whitespace changes. These make diffs harder to read and …
=> [EL-982] Fix change loop redirect bug

app/views/estimate_flow/forms/_assets.html.slim, helm_deploy/laa-estimate-eligibility/values/uat.yaml, spec/forms/assets_form_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-989)
Ensure certificated-specific helptext is only shown for certificated checks
=> EL-989: Only show self-employed help on assets screen for certificated

helm_deploy/laa-estimate-eligibility/values/uat.yaml
Previously, both branch deployments and main UAT deployments used the same `helm upgrade` command that explicitly set some dynamic values with `--set` arguments. However, now main UAT deployments use the `helm upgrade` command that staging and production deployments use, which assumes those values will be available in the values yaml file. So to get it working, we need the right values in the UAT values yaml file (which will still be overridden by the dynamic values provided on branch deployments).
Added viable default values to uat.yaml
- PR …
=> BUG: Main UAT deployments failing

app/javascript/application.js, app/views/estimates/print.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-996)
Stop using inline javascript for print buttons
Our new Content Security Policy didn't like JS embedded within the `onclick` attribute (although it seemed to allow it on localhost)
=> EL-996: Print buttons not working

app/lib/check_answers_fields.yml, app/views/estimates/_check_answer.html.slim, app/views/estimates/_check_answers_table.html.slim, spec/views/check_answers_page/client_content/property_spec.rb, spec/views/check_answers_page/partner_content/property_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1006)
Percentages on check answers page now have a `%` suffix
=> EL-1006: Add percentage signs to percentages on check answers page

app/controllers/controlled_work_document_selections_controller.rb, app/views/controlled_work_document_selections/new.html.slim, app/views/shared/_banner.html.slim, config/locales/en.yml, spec/forms/controlled_work_document_selection_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-984)
Add an alert for pensioner disregard on the CW form selection page. This is because it is not obvious from the form that the calculation has been taken into account.
=> EL-984 Pensioner disregard alert

spec/end_to_end/self_employed_spec.rb, spec/end_to_end/with_partner_spec.rb, spec/end_to_end/without_partner_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-999)
Of our 'end_to_end' specs, that fill in forms and assert expectations about the CFE payload, only some had been converted to "dual-use" specs that also send the payload to a CFE instance and assert expectations about the results page. This PR updates the rest of them to dual use.
=> EL-999: e2e-ify all remaining end_to_end specs

app/views/start/index.html.slim, config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1012)
When self-employed is disabled, make the notice about it more prominent on the start page
=> EL-1012: Make self-employment text more visible

Gemfile, Gemfile.lock, spec/features/help_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1032)
In some (but not all) environments, HelpsController isn't getting loaded by rspec, leading to a simplecov failure. This basic spec ensures the controller gets loaded.
Also, we haven't used VCR in months, so gem and its config are removed.
=> EL-1032: Get local run coverage up to 100%

config/initializers/content_security_policy.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1028)
The policy now tells the browser to send a sample of the violating scripts etc to Sentry
=> EL-1028: Collect samples for CSP reports

README.md, app/controllers/estimates_controller.rb, app/forms/applicant_form.rb, app/forms/partner_details_form.rb, app/helpers/applicant_helper.rb, app/helpers/assets_helper.rb, app/helpers/employment_helper.rb, app/lib/feature_flags.rb, app/lib/steps/income_section.rb, app/lib/steps/logic.rb, app/lib/steps/partner_section.rb, app/models/check.rb, app/services/cfe/employment_income_payload_service.rb, app/services/error_service.rb, app/views/estimate_flow/applicant.html.slim, app/views/estimate_flow/assets.html.slim, app/views/estimate_flow/forms/_assets.html.slim, app/views/estimate_flow/forms/_employment.html.slim, app/views/estimate_flow/forms/_income.html.slim, app/views/estimate_flow/partner_details.html.slim, app/views/estimate_flow/property.html.slim, app/views/estimates/_evidence.html.slim, app/views/estimates/print.html.slim, app/views/estimates/show.html.slim, app/views/feature_flags/index.html.slim, app/views/layouts/_footer.html.slim, app/views/start/index.html.slim, spec/features/feature_flags_spec.rb, spec/models/feature_flags_spec.rb, spec/services/error_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-961)
For some types of feature flags, we will now derive the value of these from the session_data on the check object. This is so that flags can be backwards compatible, and eliminate errors associated with a flag being switched on when a user check is still underway. 
Relevant flag values i.e. those changing content/flow that are not policy specific, are stored on the session_data at the beginning of a check. These are then used to determine the flag value throughout the check.
I believe time-based flags are policy specific so these are not stored on the session_data. And not all static flags would affect the user flow (cw form flag for example). So I think we need to think about whether the flag is a global flag or a session flag on a …
=> EL-961 Derive feature flags from session data, then env vars

.circleci/config.yml, README.md
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1036)
The jira/notify step has been added to the deploy jobs. This is very much like slack/notify.
It has been added to the deploy jobs using `post-steps` where it is invoked in the workflow, as this is the neatest way of passing it parameters that we don't otherwise have available (like display-case environment name, and potentially environment type in future) and avoids having to pass these through the deploy job definition purely to pass into this command.
It has been added to the build job simply as a step, as I don't think it needs any parameters.
- No unnecessary whitespace …
=> EL-1036 - Use Jira/CircleCI integration

app/controllers/status_controller.rb, app/services/health_check_service.rb, spec/requests/statuses_controller_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1030)
This way, for UAT branches, if the database pod gets cycled and the schema gets lost, the Rails pods will stop being 'live' and new pods will be brought online, which will cause migrations to run and the schema to be re-built.
=> EL-1030: The liveness check checks the database is accessible

helm_deploy/laa-estimate-eligibility/values/production.yaml, helm_deploy/laa-estimate-eligibility/values/staging.yaml, helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1021)
Currently we have the WAF enabled in "detection-only" mode, which means it never disrupts the request/response flow, so nothing shows up in the ingress logs. And we don't have our GitHub team tagged, which means we aren't allowed to see issues in the ModSec audit logs either.
This PR tags us, so that we at least have a chance to see those logs. …
=> EL-1021: Tag GH team to allow log review

app/controllers/application_controller.rb, app/controllers/estimates_controller.rb, app/controllers/start_controller.rb, helm_deploy/laa-estimate-eligibility/templates/_envs.tpl, helm_deploy/laa-estimate-eligibility/values/production.yaml, helm_deploy/laa-estimate-eligibility/values/staging.yaml, helm_deploy/laa-estimate-eligibility/values/uat.yaml, spec/controllers/start_controller_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1022)
Make it so that the start page and the new estimate path both redirect to the primary host if one is set, so that existing checks can be completed on an old host but new ones always end up on the new one.
=> EL-1022: Redirect to primary host system

app/views/shared/_disregarded_benefits_details.html.slim, config/locales/en.yml
David pointed out that we are escaping the 'nbsp' so it's visible on the page.
=> Fix nbsp issue

app/assets/stylesheets/print.scss, app/services/pdf_service.rb, app/views/estimates/print.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-986)
as covered in the comments, the problem is related to ligatures (@exonian I believe you called this as a potential problem early on, bit I evidently missed that). The css fix to the print page prevents the split on `fi `character pairs
removed the partial being used to display the service name as a H1 and added a H2 directly to the print page. 
as per:
https://usability.yale.edu/web-accessibility/articles/headings
https://www.w3.org/WAI/tutorials/page-structure/headings/#main-heading-after-navigation
there is no problem with a H2 appearing before a H1 and the H1 should be the most important part, which for us is the result.
The issue with the H2 being split  (1.4.1) cannot be exactly replicated. The fix for 1.3.1 also prevents …
=> EL-986 make pdf titles single blocks

Gemfile, Gemfile.lock
This gem is [causing an issue](https://github.com/titusfortner/webdrivers/issues/247#issuecomment-1650315937) where it expects a chrome driver to be available in a place where it isn't. It's redundant, so we can safely remove it.
=> Remove redundant webdrivers gem

app/services/metrics/for_key_metric_dashboard_service.rb, app/services/metrics/for_user_journey_dashboard_service.rb, app/services/metrics_service.rb, spec/services/metrics/for_key_metric_dashboard_service_spec.rb, spec/services/metrics/for_user_journey_dashboard_service_spec.rb, spec/services/metrics_service_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1054)
Provide the data needed to provide # of checks with forms downloaded over time and total % of eligible controlled checks with a form downloaded.
We used to have one dashboard for AnalyticsEvents data and one for CompletedUserJourney data. Now the first dashboard uses data from both tables, so I've reworked the two services to line up with the two dashboards rather than the two database tables, and renamed them accordingly
- PR description says *what* changed and *why*, with a link to …
=> EL-1054: Add new stats for key dashboard

app/controllers/application_controller.rb, app/controllers/basic_authentication_sessions_controller.rb, app/controllers/feature_flags_controller.rb, app/controllers/robots_controller.rb, app/controllers/status_controller.rb, app/lib/feature_flags.rb, app/views/basic_authentication_sessions/new.html.slim, config/locales/en.yml, config/routes.rb, helm_deploy/laa-estimate-eligibility/templates/_envs.tpl, helm_deploy/laa-estimate-eligibility/values/production.yaml, helm_deploy/laa-estimate-eligibility/values/staging.yaml, helm_deploy/laa-estimate-eligibility/values/uat.yaml, spec/features/basic_auth_spec.rb, spec/features/feature_flags_spec.rb, spec/rails_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1060)
Use basic authentication everywhere if it's switched on in config
Except robots and status controllers
Use this _instead_ of feature flag override basic auth
Leave higher-security Blazer basic auth untouched.
=> EL-1060: Site-wide basic auth

helm_deploy/laa-estimate-eligibility/values/staging.yaml
As we're a week out, this gives us a stable place to preview public beta.
=> Turn on public beta on staging

app/controllers/status_controller.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1103)
The status controller should be unaffected, when the site is put into 'maintenance mode'. This will also stop us getting sentry 'liveness' alerts, when UAT branches are deleted.
=> EL-1103: StatusController update

lib/tasks/jobs/migrations.rake
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1102)
Allow migrations to recover from an error that sometimes happens when 2 pods try to run them at the same time.
=> EL-1102: Make migration rake task more robust

app/javascript/add-another.js, app/services/check_answers/section_lister_service.rb, app/views/estimate_flow/_additional_property_section.html.slim, app/views/estimate_flow/_bank_account_section.html.slim, app/views/estimate_flow/_benefit_section.html.slim, app/views/estimate_flow/_income_section.html.slim, app/views/estimate_flow/_vehicle_section.html.slim, config/locales/en.yml, spec/views/check_answers_page/client_content/assets_spec.rb, spec/views/check_answers_page/partner_content/assets_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1099)
All 'add another' sections have labels starting at 1. Remove JS logic to allow starting at a hidden zero.
=> EL-1099: Standardise numbering of "add another" sections

README.md, app/javascript/application.js, app/views/layouts/application.html.slim, config/initializers/content_security_policy.rb, helm_deploy/laa-estimate-eligibility/templates/_envs.tpl, helm_deploy/laa-estimate-eligibility/values/production.yaml, helm_deploy/laa-estimate-eligibility/values/staging.yaml, helm_deploy/laa-estimate-eligibility/values/uat.yaml, package.json, yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1228)
Put environment-specific Sentry keys in config, and use them to init Sentry client-side error reporting, adjusting our CSP to allow it.
=> EL-1228: Add client-side Sentry monitoring

.circleci/config.yml, bin/deploy, helm_deploy/laa-estimate-eligibility/templates/_envs.tpl, helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml, helm_deploy/laa-estimate-eligibility/values/production.yaml, helm_deploy/laa-estimate-eligibility/values/staging.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1217)
This PR gets dual deployments running to old and new UAT namespaces. Alongside changes here, changes are made in Circle CI Config and `kube-secrets`. These changes are detailed on the ticket. The same approach should be able to be used for staging and prod. 
This PR also makes changes to _env.tpl and the deploy script which should set the groundwork for dual running for other environments.
We are temporarily referring the the new namespace UAT environment as `ccq-uat` so that we can deploy successfully to a different URL.
- No unnecessary whitespace changes. These make diffs …
=> EL-1217: Dual running new UAT namespace

.circleci/config.yml, helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml, helm_deploy/laa-estimate-eligibility/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL1238)
Swapped the hostname for `main` from the existing NS to the new NS
Update values files to correspond e.g oauth
Add a wait in circleci to prevent ingress conflicts
This PR is the 2nd for this ticket. It must not be merged until the redis and postgres DBs have been successfully migrated to the new NS. This merge will take the domain name offline briefly (a few minutes, likely less than 5), so even the maintenance page would not be visible to someone trying to access the site.
Part C: https://github.com/ministryofjustice/laa-estimate-financial-eligibility-for-legal-aid/pull/1065
- …
=> EL-1238 Part B: Update hostnames and values

app/controllers/change_answers_controller.rb, app/controllers/check_answers_controller.rb, app/helpers/application_helper.rb, app/views/checks/_check_answers_table.html.slim, config/routes.rb, spec/flows/change_answers_flow_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1236)
* Renamed CheckAnswersController to ChangeAnswersController (because "Check answers" is how we describe the check answers screen, and having it also mean where you go _from_ that screen was confusing me).
* In ChangeAnswersController, use temporary copy of the session data that we keep in a key called 'pending', and only override the main session data with the temporary copy when we complete a loop 
The session_data method in ChangeAnswersController overrides the default method in ApplicationController
- No unnecessary whitespace changes. These make diffs harder to read and …
=> EL-1236: pending answers in change answer loops

.circleci/config.yml
Now that we have switched to the new NS we can stop deploying to the old NS. This will save us on circle credits as we have been using more over the last few weeks as we have been dual deploying.
=> Remove deployment to old NS from circle config

config/initializers/devise.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1231)
Devise's automatic secret key lookup tries a deprecated Rails function. So we avoid the automatic lookup. 
=> EL-1231: Remove deprecation warning

.github/workflows/combine-prs.yml, .github/workflows/delete_uat_release.yml
Our GitHub actions were trying to use secrets that no longer existed to delete releases from the now-removed old UAT namespace. This fixes that.
=> Remove attempt to interact with old UAT namespace

app/models/concerns/property_summarisable.rb, spec/models/controlled_work_document_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1282)
A typo meant that when displaying the combined outstanding mortgage for all non-smod properties, we were always returning 0. This fixes that and adds a test.
=> EL-1282: Mortgage not showing on CW forms

app/models/check.rb, app/views/checks/end_of_journey.html.slim, config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1278)
- Removing references to evidence gathering and 'evidence you might need' on ‘You’ve reached the end of this service' screen in the controlled work flow when a client is under 18 and doesn’t need a means test. 
N/A
=> EL-1278: Update to view and added in some check methods.

spec/system/accessibility_spec.rb, spec/system/add_another_spec.rb, spec/system/feedback_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1290)
added a `:slow` tag to 12 tests, all of which were taking longer than 3 seconds each.
removed one journey from the AXE tests so now we only check `certificated`. The `certificated` AXE test takes longer but covers more of the journey, however if we feel that as we reuse components, nothing would be missed if we used `controlled` I am happy to switch to that journey. 
to run the tests locally without the slow tests: 
`bundle exec rspec -tag=~slow`
- PR description says *what* changed …
=> EL-1290 speed up testing

spec/end_to_end/asylum_support_spec.rb
A change in CFE behaviour caused the asylum support journey to break. This is the kind of thing that would have been caught by an E2E test, and because asylum support involves a unique interaction between CCQ and CFE I think it's a good candidate for an E2E test anyway.
=> Add asylum support e2e spec

helm_deploy/laa-estimate-eligibility/templates/ingress.yaml, helm_deploy/laa-estimate-eligibility/templates/metabase/metabase-deployment.yaml, helm_deploy/laa-estimate-eligibility/templates/metabase/metabase-service.yaml, helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml, helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml, helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1294)
add metabase deployment and service yaml files
update ingress to point metabase at new hostname
When metabase is enabled in UAT this deployment fails because it cannot read the secret 'metabase'. This secret only exists on staging at present. 
I have confirmed that it creates a metabase pod and it is during this process that the metabase secret is required.
Once this PR is reviewed and it deploys to staging there will to be further work to get metabase working and to hide it behind authentication.
- No unnecessary whitespace changes. These make diffs harder to read and conflicts …
=> EL-1294 add metabase 

helm_deploy/laa-estimate-eligibility/templates/ingress.yaml, helm_deploy/laa-estimate-eligibility/templates/metabase/metabase-service.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1294)
removed `-service` suffix from metabase service name, as when the rest of the name is applied (64 characters total) it exceeds the allowed character count of 63 characters
=> EL-1294 Bugfix: rename to reduce character count

app/lib/steps/logic.rb, app/models/calculation_result.rb, app/models/check.rb, app/services/cfe/applicant_payload_service.rb, app/services/cfe/assessment_payload_service.rb, app/services/cfe/proceedings_payload_service.rb, app/views/checks/_check_answers_table.html.slim, app/views/results/_result_panel_content.html.slim, app/views/results/_under_eighteen.html.slim, app/views/results/_under_eighteen_next_steps.html.slim, app/views/results/download.html.slim, app/views/results/show.html.slim, config/locales/en.yml, spec/end_to_end/asylum_support_spec.rb, spec/end_to_end/passporting_spec.rb, spec/end_to_end/under_eighteen_spec.rb, spec/end_to_end/without_partner_spec.rb, spec/services/cfe/applicant_payload_service_spec.rb, spec/views/results_page/under_eighteen_content_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1255)
- Remove deprecated applicant params from CFE payload
- Only send proceeding type to CFE if it's relevant
- Results page can cope with absence of proceeding types
- Send new u18 params to CFE
- Add new u18-specific results page content
- New e2e tests and results page view specs
E2E tests will fail until both https://github.com/ministryofjustice/cfe-civil/pull/463 and https://github.com/ministryofjustice/cfe-civil/pull/470 are merged.
- PR description says *what* changed and *why*, …
=> EL-1255: Under-18 results

app/lib/steps/outgoings_section.rb
The outgoings section was always asking the property question even in situations where capital questions should be skipped.
=> BUG: When forms are reordered, property isn't skipped when means test should be skipped

.circleci/config.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1318)
The circleci orb browser-tools installs a few browsers by default. we currently only use chrome. the firefox install was taking 22 seconds and we dont use it so this PR stops these unused browsers being installed.
This PR also stops specifying the version of chrome and will use an existing chrome if it is available. The issue that required us to do this appears to have been fixed in an update to the orb
- …
=> EL-1318 in circle only install required browsers

.circleci/config.yml
Reduce parallel runs to 3 to check if build and push starts sooner and to check how lomng run specs tales to see if 3 is the optimal size
b&p is unaffected by the changes to parallelisation however 3 appears to be optimal for us, the actual specs run for about a minute in each with about 1 minuteof setup for each run.
- Commit messages say why …
=> reduce parallel runs to 3

spec/system/add_another_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1316)
Only look at page contents for session specs (because on CI, for some reason, trying to retrieve session values from `page.get_rack_session` started being flaky). This makes the system test more pure - instead of knowing that stuff is stored in the session, all it needs to know is that if you save a page of data and then go back to it, there are certain IDs of HTML input elements that should be where the information you've saved should be repopulated.
- PR description says *what* …
=> EL-1316: Flaky spec

app/lib/feature_flags.rb, helm_deploy/laa-estimate-eligibility/templates/_envs.tpl, helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml, helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml, helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml, spec/rails_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1323)
Add feature flag for early eligibility in preparation for the work.
Also remove `UNDER_EIGHTEEN_FEATURE_FLAG`  from env vars template file as just spotted that I think we forgot to do this.
=> EL-1323: Add early eligibility feature flag

Gemfile.lock
No ticket
ARM M1 with Sonoma OS is a new platform for the project, and so needs to be added to Gemfile.lock
=> Add arm64-darwin-23 to platforms in Gemfile.lock

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, puppeteer.config.cjs
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1320)
- Publishing a custom docker image, extending `cimg/ruby:3.2.2-browsers`
- This reduces `run_specs` steps for each parallelised test, by having the set-up in the executor
- Removed `puppeteer.config.cjs` which is not needed - as this was used to point to where puppeteer needing to find things in the project for it to run
- Added `ENV` variables to the docker file, which points to a constant place where puppeteer can find Chrome - as per my understanding of the [documentation](https://pptr.dev/guides/configuration) 
- Have got this to work on 2 other branches https://github.com/ministryofjustice/laa-check-client-qualifies/pull/1219/files & https://github.com/ministryofjustice/laa-check-client-qualifies/pull/1221/files - but want a …
=> EL-1320: Custom docker image for `test-executor`, adding an `ENV` value for puppeteer

app/models/calculation_result.rb, app/models/cfe_result.rb
https://dsdmoj.atlassian.net/browse/EL-1308
Split out the 'parse and interpret Cfe result' from 'display result on results page' logic so that the CfeResult can be used (and extended) to allow early eligibility to check things like 'amount over the threshold' and 'gross_income_ineligible?' from the CfeResult without the formatting code currently in CalculationResult.
CalculationResult is currently in the models directory, looks (certainly now) more like a 'presenter' object that extracts common code to do with displaying (e.g consistent formatting for monetary values) 
- No unnecessary whitespace changes. These make diffs harder to read …
=> EL-1308 spike to split out interpreting Cfe data from display

spec/end_to_end/result_page_variations_spec.rb, spec/end_to_end/self_employed_spec.rb, spec/end_to_end/with_partner_spec.rb, spec/end_to_end/without_partner_spec.rb, spec/support/flow_helpers.rb
https://dsdmoj.atlassian.net/browse/EL-1308
Change default income frequency to monthly so that tests are not creating ineligible cases by default
=> El 1308 change income default units

app/views/devise/sessions/new.html.slim, app/views/layouts/_admin_login.html.slim, app/views/layouts/application.html.slim, app/views/layouts/devise.html.slim, app/views/layouts/shared/_header.html.slim, app/views/start/index.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1308)
Small refactor of where the flash notice is displayed. Previously it was in application.html.slim but if we use it for the EE feature, we need better control of where it displays. Currently it is only used in the admin stuff (I think) so this refactor moves this code to a specific partial for that, which is only rendered by a new layout devise.html.slim (which is rendered for the authentication flows only).
The HTML head section is moved to a new partial to prevent duplication between the 2 layouts
- No unnecessary whitespace changes. These make diffs harder to read and …
=> EL-1372 Move flash logic into admin partial

spec/flows/change_answers_flow_spec.rb, spec/support/flow_helpers.rb
https://dsdmoj.atlassian.net/browse/EL-1308
While developing EL-1308, a small change was made to a fixture to use named parameters rather than passing a hash. The result was finding a test which passed an incorrect (presumably out of date) parameter which had no effect.
n/a
=> Fix a defective flow spec found during EL-1308 work

.circleci/config.yml
No ticket
Needed to alter AWS ERB orb version, as the version we were using no longer exists after circle upgraded it. I have loosened the version specification to prevent this issue recurring
=> loosen ECR orb specification to cope with bug fixes and upgrades

app/services/cfe/regular_transactions_payload_service.rb, app/services/cfe_param_builders/regular_transactions.rb, spec/services/cfe/regular_transactions_payload_service_spec.rb
https://dsdmoj.atlassian.net/browse/EL-1377
Don't send income or outgoings forms to CFE if their contents is invalid
We had a crash on production due to trying to send an invalid outgoings form - https://ministryofjustice.sentry.io/issues/4999162546/?project=4504177640275968&query=&referrer=project-issue-stream.
It would seem sensible to add guards to prevent this scenario for occurring, hence this change - although its not exactly clear what the user did to cause this error 
- PR description says *what* changed and *why*, with a link to the …
=> EL-1377 dont try to send income or outgoings forms if they are invalid

app/assets/stylesheets/results.scss, app/controllers/results_controller.rb, app/models/calculation_result.rb, app/views/results/_capital_table.html.slim, app/views/results/_outgoings_table.html.slim, app/views/results/_summary.html.slim, config/locales/en.yml, spec/end_to_end/result_page_variations_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1385)
show "not assessed" panels when the user has arrived at the results page from an early eligibility result.
ensure that the assessed panels show if they continue the journey and submit a full set of answers
=> EL-1385 EE results page

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1352
After merging EL-1352, we needed to remove the branch-specific code around the image used in the pipeline. This makes non-main builds work again
=> EL-1352 follow-up - remove left-over testing artifacts

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, package.json, yarn.lock
No ticket
Puppeteer upgrade still needs a small helping hand
=> Upgrade puppeteer to 22.6.0

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, package.json, yarn.lock
No ticket
Upgrade puppeteer to 22.6.2 - new version of chrome
=> Upgrade puppeteer to 22.6.2 with new chrome version

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, package.json, yarn.lock
No Ticket
Puppeteer upgrade to 22.7.1 
This manual upgrade is always needed every few weeks in line with Chrome releases
=> Upgrade puppeteer to 22.7.1

app/lib/feature_flags.rb, spec/forms/mortgage_or_loan_payment_form_spec.rb, spec/forms/property_entry_form_spec.rb, spec/forms/property_form_spec.rb, spec/rails_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1551)
Convert MTR accelerated into a global flag due to general election pushing back the SI implementation date 
=> EL-1551 convert MTR accelerated into a global feature flag

db/migrate/20240614095308_remove_blazer.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1492)
Revert the tidy up of the blazer role, as it turned out to be more difficult than expected on CP (Permission denied error)
This PR should have a revert created once merged, to form the basis of a new ticket to do the tidy-up
=> EL-1492 Remove tidy up from blazer migration

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, package.json, yarn.lock
No ticket
Puppeteer 22.15 upgrade
=> Puppeteer 22.15 upgrade to Chrome 127

spec/features/provider_authentication_spec.rb
No Ticket
The ProviderAuth spec fails 1/256 times due to using String.random which can generate null bytes which our DB doesn't like. Change it to AlphaNumeric.alpha so that random failures stop happening
=> Use AlphaNumeric.alpha rather than String.random

.github/dependabot.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1693)
Remove Rails and puppeteer from dependabot combined dependency lists. These create unmergeable PRs which block other more important (e.g. security) related PRs
=> EL-1693 exclude Rails and puppeteer from combined dependency lists

.github/actions/delete-uat-release/action.yml
-[El-1640](https://dsdmoj.atlassian.net/browse/EL-1640)
Removing delete command for PVC. No longer needed as we now use Helm Deploy. Will remove errors after every PR merge going forward.
=> EL-1640 Removing delete pvc command. Not required

app/views/question_flow/_additional_property_section.html.slim, config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1633)
- display hint text based on `#{i18n_key}`
- partner `#{i18n_key}` hint text key value is blank
- n/a
=> EL-1633: Remove text from Partner Other property details page

app/lib/feature_flags.rb, helm_deploy/laa-estimate-eligibility/templates/_envs.tpl, helm_deploy/laa-estimate-eligibility/values/ccq-production.yaml, helm_deploy/laa-estimate-eligibility/values/ccq-staging.yaml, helm_deploy/laa-estimate-eligibility/values/ccq-uat.yaml, spec/rails_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1730)
Added a global feature flag for the updated CW forms. The ticket does not specify session or global, and I think when we release this we want everyone to use the new form regardless of when the session was started. This will not break anything as the data will exist in the session for the new inputs on the forms and if the data does not exist then we handle that in the forms themselves anyway.
- Diff has …
=> EL-1730 Add Feature Flag for CW Form Updates

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, package.json, yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1689)
- manual upgrade of puppeteer to 23.4.0
- n/a
=> EL-1689: Puppeteer 23.4.0 upgrade to Chrome 129.0.6668.58

.github/workflows/gajira.yml
according to this:
https://stackoverflow.com/questions/71481086/is-pull-request-label-available-to-a-github-action
We can get the labels into an array and compare them to trigger the job
As dependabot also adds more than 1 label this should allow us to cater for occassions where there are multiple labels too
- Commit messages say why the change …
=> EL-1726 Bugfix Gajira GH action

app/controllers/providers/omniauth_callbacks_controller.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1706)
remove the session_reset command as it was not achieving its intended aim
=> El 1706 remove session reset

.github/workflows/gajira.yml
- remove process job and use PR variables as they are
=> EL-1726: Gajira part 4

app/models/completed_user_journey.rb, db/migrate/20241010143225_add_early_result_type_to_completed_user_journeys.rb, db/schema.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1756)
- add `early_result_type` to CompletedUserJourney
- n/a
=> EL-1756: Add `early_result_type` to CompletedUserJourney

app/models/check.rb, app/services/check_answers/section_lister_service.rb, spec/flows/early_result_spec.rb, spec/flows/under_eighteen_flow_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1745)
Added a check to see if we are responding to an EE gross income result
If we are we display only relevant sections on Check ANswers
=> EL-1745 Check Answers display

app/lib/feature_flags.rb, spec/forms/mortgage_or_loan_payment_form_spec.rb, spec/forms/property_entry_form_spec.rb, spec/forms/property_form_spec.rb, spec/rails_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1853)
reverts the MTR feature flag to be tme based and sets it to turn on on 20th November 2024
=> EL-1853 revert feature flag to be time based and update tests

app/views/question_flow/benefits.html.slim, app/views/question_flow/forms/_benefit_details.html.slim, app/views/question_flow/forms/_benefits.html.slim, app/views/question_flow/forms/_other_income.html.slim, app/views/question_flow/other_income.html.slim, app/views/question_flow/partner_other_income.html.slim, app/views/shared/_cost_of_living.html.slim, app/views/shared/_cost_of_living_payments.html.slim, app/views/shared/_disregarded_benefits_details.html.slim, config/locales/en.yml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1865)
add conditional content on `benefits`, `benefit-details` and `other-income` pages
the change to make `non-passporting` appear on a single line is not behind a feature flag as it is not MTR specific 
=> EL-1865 CCQ MTR accelerated content updates: Benefits

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, package.json, yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1895)
- manual upgrade of puppeteer to 23.9.0
- n/a
=> EL-1895: Manual upgrade of puppeteer to 23.9.0

.circleci/config.yml, Gemfile, Gemfile.lock, README.md, db/data/20241101122511_populate_early_eligibility_result_in_completed_user_journeys.rb, db/data_schema.rb, db/schema.rb, lib/tasks/jobs/migrations.rake
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1833)
added a new gem to handle data_migrations.
This is our first data_migration and although we don't expect to have many of these, they have a way of sneaking up on you as the db is modified. So it makes sense to add this now as you cant retrospectively move migrations.
The migration runs on my machine ;)
I tested it on early_eligibility_selection does not exist, is gross and is continue_check
It will not do anything on UAT as the branch is new and will have no data. it will work on main UAT when it is merged. As such I have added 2 approval steps, one for STG and one for PROD. This way we can merge to main and then test each namespace before and after the migration.
The data_migration uses :with_data to do the data migrations after …
=> EL-1833 (part 2) add data_migration

app/views/results/show.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1810)
- add button id for GA4
- will need to test this UAT link in Google Tag Manager "Preview" 
- Tags & triggers have been made in Google Analytics
=> EL-1810: Track when results are saved as PDF

.circleci/config.yml
Uncomment the production deploy approval step so that production deploys need to be manually approved.
Why? we dont want to deploy over xmas and new year, but we still want to be able to merge tickets to prevent conflicts arising in january when we try to merge a bunch of tickets.
I
=> Add a production hold to deployments

.circleci/config.yml
- Reversing https://github.com/ministryofjustice/laa-check-client-qualifies/pull/1708 , as we are now into the new year.
- n/a
=> Remove production hold to deployments

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, package.json, yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2053)
- update puppeteer from 24.0.0 to 24.1.0
- n/a
=> EL-2053: update puppeteer from 24.0.0 to 24.1.0

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, package.json, yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2068)
Bump puppeteer from 24.1.0 to 24.1.1.
=> el-2068 Bump puppeteer from to 24.1.1

lib/tasks/populate_feedback_page.rake, spec/lib/tasks/populate_feedback_page_spec.rb, spec/spec_helper.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2064)
Update SatisfactionFeedbacks with nil page values.
On production there are 189 SatisfactionFeedbacks with page nil
I have tested this locally and in UAT, by creating 200 SatisfactionFeedback records using this script
```
100.times do
SatisfactionFeedback.create(satisfied: "yes", level_of_help: "certificated", outcome: "eligible", comment: "This is a comment made for testing purposes. Please ignore this comment.")
end
100.times do
SatisfactionFeedback.create(satisfied: "yes", level_of_help: "controlled", outcome: "eligible", comment: "This is a comment made for testing purposes. Please ignore this comment.")
end
```
and then runing the rake task. Both locally and in uat the rake task completed and updated the page value on all 200 …
=> el-2064: create rake task to populate satisfaction feedback pages

app/lib/feature_flags.rb, app/models/dependant_income_model.rb, spec/forms/dependant_details_form_spec.rb, spec/models/dependant_income_model_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2160)
add time based feature flag and update the `dependant_monthly_upper_limit`
The ticket references partner allowance but that comes from the CFE response so is done on the CFE ticket, we will need to UAT that change on that ticket, comments to this affect added to both JIRA tickets
I had an issue with a misbehaving test, details are here: https://mojdt.slack.com/archives/C040DEGBZQQ/p1742399721684899
Hence the comment on the spec file that indicates a test will break on 7th April
- PR …
=> EL-2130 add threshold flag and dependant rate

app/controllers/change_answers_controller.rb, spec/flows/change_answers_flow_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2194)
Show the user the `cannot-use-service` page when there are multiple owners
add tests for the change answers flow to trigger the page
this has been taken from the original EL-2194 but just handles the exit page requirements from that ticket
=> EL-2194 show exit page when multiple owners

lib/tasks/delete_feedback.rake, spec/lib/tasks/delete_feedback_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2213)
This rake task deletes unwanted feedback from the SatisfactionFeedback table.
It can be run as follows `rake "migrate:delete_feedback[false, '2025-03-27 14:07:00', '2025-03-27 23:23:00']"`
which would delete 1470 records as specified in ticket
When run with the first argument as true the rake task outputs the number of records that would be deleted without actually deleting any records, to allow for testing.
I have tested this locally and in uat by running the following script to create 2000 satisfaction feedback records and then running the rake task to delete these records - both locally and in uat the rake task completed almost instantly (in  <5 seconds).
```
2000.times do
SatisfactionFeedback.create(satisfied: "yes", …
```
=> el-2213: add rake task to delete feedbacks

app/models/check.rb, app/views/question_flow/_early_result_banner.html.slim, spec/flows/early_result_spec.rb
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2305)
Don't show ee banner if the check is for a passported client.
=> el-2305: prevent ee banner being displayed for passported checks

app/models/issue.rb, app/views/updates/index.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2368)
For discussion:
I have been unable to recreate the sentry issue in the above ticket, either locally or on uat main. I have tried using the bullet gem but that still didn't identify any n+1 query on the start/index page.
Bullet did identify an n+1 issue with our use of ActionText, however, this only affects the updates/index page (/updates). I have added a fix to app/views/updates/index.html.slim as outlined here https://guides.rubyonrails.org/action_text_overview.html#avoiding-n-1-queries to try and address this issue.
I have also made a change to app/models/issue.rb in the hope that it might resolve the Sentry alerts in the ticket, but without being able to recreate the issue I have low confidence that the fix will work. The fix …
=> el-2368: Use eager loading for issue updates

Dockerfile
We need to update psql-client in order to be able to run pg_dump. Currently we are getting a server version mismatch error if we try to run pg_dump on a pod. This will allow us to test pg_dump on uat-main and staging.
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2409)
=> el-2409-part-1: update psql-client

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, package.json, yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2446)
- If applied, this updates puppeteer to 24.10.2
- n/a
=> EL-2446: bump puppeteer from 24.10.1 to 24.10.2

app/controllers/results_controller.rb, app/models/calculation_result.rb, app/views/results/_capital_table.html.slim, app/views/results/_outgoings_table.html.slim, app/views/results/_summary.html.slim
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2291)
Remove references to early_eligibility_selection - these are no longer required now that the early_eligibility feature flag has been removed.
=> el-2391: remove references to early_eligibility_selection

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, package.json, yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2485)
- If applied, this updates puppeteer to 24.11.2
- This relates to this PR: https://github.com/ministryofjustice/laa-check-client-qualifies/pull/1916
=> EL-2485: Update puppeteer to 24.11.2

lib/tasks/delete_analytics_event_via_assessment_code.rake, lib/tasks/delete_analytics_event_via_time_frame_open.rake, lib/tasks/delete_feedback.rake
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2268)
- If applied, this adds 2 rake tasks to delete unwanted AnalyticEvent data.
- Will have 2 rake tasks;
1. to delete AnalyticEvent data by specific assessment codes
2. to delete AnalyticEvent data by how long the event data has been open (30 days or more to be removed)
- this will also remove AnalyticEvent data where there is an incorrect assessment code 
- You will have to take a copy of [production DB and restore it locally ](https://dsdmoj.atlassian.net/wiki/spaces/laagetaccess/pages/5761859722/Taking+a+copy+of+the+CCQ+production+database+and+restoring+locally) in order to verify you are targeting the correct data. 
- Branch is generally up to date …
=> EL-2268: Delete SQL attack data from AnalyticEvent table

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, package.json, yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2551)
- If applied, this updates "puppeteer" to "24.15.0"
- n/a
=> EL-2551: Update "puppeteer" to "24.15.0"

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, package.json, yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2639)
- If applied, this updates puppeteer to 24.20.0
- this will resolve this PR -> https://github.com/ministryofjustice/laa-check-client-qualifies/pull/1968
=> EL-2639: Update puppeteer to 24.20.0

.circleci/config.yml, .github/workflows/browser_tools_docker_image.yml, Dockerfile_browser_tools.dockerfile, package.json, yarn.lock
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2672)
- If applied, this updates puppeteer to 24.22.3
- This will resolve this pr -> https://github.com/ministryofjustice/laa-check-client-qualifies/pull/1990
=> EL-2672: Update to puppeteer 24.22.3 (attempt 2)
